"""
===============================================================================
Pendle YT Yield Strategy -- Leveraged Floating Yield on Arbitrum
===============================================================================

Buy Yield Tokens (YT) on Pendle instead of Principal Tokens (PT).

PT is a bond-like position: fixed yield locked at a discount, redeemable 1:1
at maturity. YT is the opposite: a leveraged bet on *floating* yield rates.
YT holders receive all the yield generated by the underlying over the remaining
period, but YT decays toward zero at maturity if yield comes in below implied.

WHAT THIS STRATEGY DOES:
------------------------
1. Check wstETH balance
2. When sufficient: swap wstETH -> YT-wstETH-25JUN2026 via Pendle
3. Hold YT for yield accrual
4. Teardown: swap YT back to wstETH via Pendle

KEY DIFFERENCES FROM demo_pendle_basics (PT):
---------------------------------------------
- PT uses swapExactSyForPt -> fixed yield, bond-like, low risk
- YT uses swapExactTokenForYt -> leveraged floating yield, high risk
- YT includes ApproxParams for binary search of optimal flash swap size
- YT decays to zero at maturity if yield < implied

USAGE:
------
    almanak strat run -d strategies/demo/pendle_yt_yield --network anvil --once

===============================================================================
"""

import logging
from datetime import UTC
from decimal import Decimal
from typing import TYPE_CHECKING, Any

from almanak.framework.intents import Intent

if TYPE_CHECKING:
    from almanak.framework.teardown import TeardownMode, TeardownPositionSummary

from almanak.framework.strategies import (
    IntentStrategy,
    MarketSnapshot,
    almanak_strategy,
)
from almanak.framework.utils.log_formatters import format_usd

logger = logging.getLogger(__name__)


@almanak_strategy(
    name="pendle_yt_yield",
    description="Leveraged floating yield exposure via Pendle YT on Arbitrum",
    version="1.0.0",
    author="Almanak",
    tags=["demo", "pendle", "yield", "yt", "leveraged-yield", "arbitrum"],
    supported_chains=["arbitrum"],
    supported_protocols=["pendle"],
    intent_types=["SWAP", "HOLD"],
    default_chain="arbitrum",
)
class PendleYTYieldStrategy(IntentStrategy):
    """Pendle YT strategy -- buy YT-wstETH for leveraged yield exposure.

    YT (Yield Token) represents a claim on all floating yield until maturity.
    If actual yield exceeds the implied yield at purchase, the position profits.
    YT has convex upside (unlimited yield upside) but time decay risk.

    Configuration Parameters (from config.json):
    - market: Pendle market address
    - market_name: Human-readable market name
    - trade_size_token: Amount of wstETH to swap into YT
    - max_slippage_bps: Maximum slippage in basis points
    - base_token: Input token (WSTETH)
    - yt_token: YT token name (YT-wstETH-25JUN2026)
    - stop_loss_pct: Stop-loss as % of entry value (default 50)
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

        # Market configuration
        self.market = self.get_config("market", "0xf78452e0f5c0b95fc5dc8353b8cd1e06e53fa25b")
        self.market_name = self.get_config("market_name", "wstETH-25JUN2026")

        # Trading parameters
        self.trade_size_token = self.get_config("trade_size_token", None)
        if self.trade_size_token is not None:
            self.trade_size_token = Decimal(str(self.trade_size_token))
        self.trade_size_usd = Decimal(str(self.get_config("trade_size_usd", "10")))
        self.max_slippage_bps = int(self.get_config("max_slippage_bps", 200))

        # Token configuration
        self.base_token = self.get_config("base_token", "WSTETH")
        self.base_token_symbol = self.get_config("base_token_symbol", self.base_token)
        self.yt_token = self.get_config("yt_token", "YT-wstETH-25JUN2026")
        self.yt_token_symbol = self.get_config("yt_token_symbol", "YT-wstETH")

        # Risk parameters
        self.stop_loss_pct = int(self.get_config("stop_loss_pct", 50))
        # YT tokens are illiquid near maturity — use a wider teardown slippage
        # Default 1500bps (15%) for HARD mode, 500bps (5%) for SOFT mode
        self.teardown_hard_slippage_bps = int(self.get_config("teardown_hard_slippage_bps", 1500))
        self.teardown_soft_slippage_bps = int(self.get_config("teardown_soft_slippage_bps", 500))
        for _name, _bps in (
            ("teardown_hard_slippage_bps", self.teardown_hard_slippage_bps),
            ("teardown_soft_slippage_bps", self.teardown_soft_slippage_bps),
        ):
            if not 0 <= _bps <= 10_000:
                raise ValueError(f"{_name} must be between 0 and 10000 bps, got {_bps}")

        # State
        self._has_entered_position = False
        self._consecutive_holds = 0
        self._entry_value_usd = Decimal("0")

        trade_size_display = (
            f"{self.trade_size_token} {self.base_token_symbol}"
            if self.trade_size_token
            else f"${self.trade_size_usd}"
        )
        logger.info(
            f"PendleYTYieldStrategy initialized: "
            f"market={self.market_name}, "
            f"yt_token={self.yt_token}, "
            f"trade_size={trade_size_display}, "
            f"slippage={self.max_slippage_bps}bps, "
            f"stop_loss={self.stop_loss_pct}%"
        )

    def decide(self, market: MarketSnapshot) -> Intent | None:
        """Decide whether to buy YT or hold.

        Logic:
        1. If no position: buy YT with wstETH
        2. If position exists: hold (in production, would monitor yield vs implied)
        """
        # Get base token price
        try:
            base_price = market.price(self.base_token)
            logger.debug(f"Current {self.base_token_symbol} price: ${base_price:,.2f}")
        except ValueError:
            logger.warning(f"Could not get {self.base_token} price")
            return Intent.hold(reason="Price data unavailable")

        # Check balance
        try:
            base_balance = market.balance(self.base_token)
            logger.debug(
                f"Balance - {self.base_token}: {base_balance.balance:.6f} "
                f"(${base_balance.balance_usd:,.2f})"
            )
        except ValueError as e:
            logger.warning(f"Could not get balance: {e}")
            return Intent.hold(reason="Balance data unavailable")

        # If no position yet, enter
        if not self._has_entered_position:
            # Check sufficient balance
            if self.trade_size_token:
                if base_balance.balance < self.trade_size_token:
                    return Intent.hold(
                        reason=f"Insufficient {self.base_token} "
                        f"({base_balance.balance:.6f} < {self.trade_size_token})"
                    )
            elif base_balance.balance_usd < self.trade_size_usd:
                return Intent.hold(
                    reason=f"Insufficient {self.base_token} "
                    f"(${base_balance.balance_usd:.2f} < ${self.trade_size_usd})"
                )

            # Buy YT
            self._has_entered_position = True
            self._consecutive_holds = 0

            if self.trade_size_token:
                self._entry_value_usd = self.trade_size_token * Decimal(str(base_price))
                logger.info(
                    f"Buying YT: {self.trade_size_token} {self.base_token} -> {self.yt_token} "
                    f"(~{format_usd(self._entry_value_usd)})"
                )
                return Intent.swap(
                    from_token=self.base_token,
                    to_token=self.yt_token,
                    amount=self.trade_size_token,
                    max_slippage=Decimal(str(self.max_slippage_bps)) / Decimal("10000"),
                    protocol="pendle",
                )
            else:
                self._entry_value_usd = self.trade_size_usd
                logger.info(
                    f"Buying YT: {format_usd(self.trade_size_usd)} {self.base_token} -> {self.yt_token}"
                )
                return Intent.swap(
                    from_token=self.base_token,
                    to_token=self.yt_token,
                    amount_usd=self.trade_size_usd,
                    max_slippage=Decimal(str(self.max_slippage_bps)) / Decimal("10000"),
                    protocol="pendle",
                )

        # Already in position -- hold
        self._consecutive_holds += 1
        return Intent.hold(
            reason=f"Holding {self.yt_token} position "
            f"(hold #{self._consecutive_holds}, "
            f"entry ~{format_usd(self._entry_value_usd)})"
        )

    def _get_tracked_tokens(self) -> list[str]:
        """Tokens to track for wallet balance."""
        return [self.base_token_symbol, self.yt_token_symbol]

    def get_status(self) -> dict[str, Any]:
        """Get current strategy status for monitoring."""
        return {
            "strategy": "pendle_yt_yield",
            "chain": self.chain,
            "wallet": self.wallet_address[:10] + "..." if self.wallet_address else "N/A",
            "config": {
                "market": self.market_name,
                "yt_token": self.yt_token,
                "trade_size": str(self.trade_size_token or self.trade_size_usd),
                "max_slippage_bps": self.max_slippage_bps,
                "stop_loss_pct": self.stop_loss_pct,
            },
            "state": {
                "has_position": self._has_entered_position,
                "entry_value_usd": str(self._entry_value_usd),
                "consecutive_holds": self._consecutive_holds,
            },
        }

    # =========================================================================
    # Teardown
    # =========================================================================

    def supports_teardown(self) -> bool:
        return True

    def get_open_positions(self) -> "TeardownPositionSummary":
        """Get summary of open positions for teardown."""
        from datetime import datetime

        from almanak.framework.teardown import (
            PositionInfo,
            PositionType,
            TeardownPositionSummary,
        )

        positions: list[PositionInfo] = []

        if self._has_entered_position:
            positions.append(
                PositionInfo(
                    position_type=PositionType.TOKEN,
                    position_id="pendle_yt_0",
                    chain=self.chain,
                    protocol="pendle",
                    value_usd=self._entry_value_usd,
                    details={
                        "market": self.market_name,
                        "yt_token": self.yt_token,
                        "base_token": self.base_token,
                    },
                )
            )

        return TeardownPositionSummary(
            strategy_id=getattr(self, "strategy_id", "pendle_yt_yield"),
            timestamp=datetime.now(UTC),
            positions=positions,
        )

    def generate_teardown_intents(self, mode: "TeardownMode", market=None) -> list[Intent]:
        """Generate intents to close YT position.

        Swaps YT back to the base token via Pendle.

        NOTE: YT tokens are inherently illiquid near maturity because their
        value decays toward zero as implied yield is realized. The teardown
        uses significantly wider slippage (default 15% HARD, 5% SOFT) to
        account for thin AMM liquidity. If the YT cannot be sold even at
        max slippage, the TeardownManager will escalate further.
        """
        from almanak.framework.teardown import TeardownMode

        if not self._has_entered_position:
            return []

        # Use wider slippage — YT AMMs are thin near maturity
        if mode == TeardownMode.HARD:
            max_slippage = Decimal(str(self.teardown_hard_slippage_bps)) / Decimal("10000")
        else:
            max_slippage = Decimal(str(self.teardown_soft_slippage_bps)) / Decimal("10000")

        logger.info(
            f"Generating teardown: swap {self.yt_token} -> {self.base_token} "
            f"(mode={mode.value}, slippage={max_slippage:.2%})"
        )

        # Swap YT back to base token via Pendle
        return [
            Intent.swap(
                from_token=self.yt_token,
                to_token=self.base_token,
                amount="all",
                max_slippage=max_slippage,
                protocol="pendle",
            )
        ]


# =============================================================================
# Entry Point
# =============================================================================

if __name__ == "__main__":
    print("=" * 60)
    print("PendleYTYieldStrategy - Demo Strategy")
    print("=" * 60)
    print(f"\nStrategy Name: {PendleYTYieldStrategy.STRATEGY_NAME}")
    print(f"Version: {PendleYTYieldStrategy.STRATEGY_METADATA.version}")
    print(f"Supported Chains: {PendleYTYieldStrategy.SUPPORTED_CHAINS}")
    print(f"Supported Protocols: {PendleYTYieldStrategy.SUPPORTED_PROTOCOLS}")
    print(f"Intent Types: {PendleYTYieldStrategy.INTENT_TYPES}")
    print(f"\nDescription: {PendleYTYieldStrategy.STRATEGY_METADATA.description}")
    print("\nTo run this strategy:")
    print("  almanak strat run -d strategies/demo/pendle_yt_yield --network anvil --once")
