"""Unit tests for MarketSnapshot.position_health() on the strategy-layer shim.

These tests guard against the regression where the shim diverged from the
data-layer canonical and templates generated by `almanak strat new --template
lending_loop` raised AttributeError on `market.position_health(...)` every
iteration after the first.
"""

from decimal import Decimal
from unittest.mock import MagicMock, patch

import pytest

from almanak.framework.data.position_health import PositionHealth
from almanak.framework.market import MarketSnapshot


def _sample_health() -> PositionHealth:
    return PositionHealth(
        health_factor=Decimal("1.85"),
        collateral_value_usd=Decimal("1000"),
        debt_value_usd=Decimal("400"),
        lltv=Decimal("0.85"),
        max_borrow_usd=Decimal("450"),
        protocol="aave_v3",
        market_id="aave_v3",
    )


class TestPositionHealthAttributeExists:
    def test_class_has_position_health(self):
        # Regression guard for the user's deployed agent bug:
        # `'MarketSnapshot' object has no attribute 'position_health'`.
        assert hasattr(MarketSnapshot, "position_health")

    def test_class_has_set_position_health(self):
        assert hasattr(MarketSnapshot, "set_position_health")

    def test_init_accepts_gateway_client(self):
        market = MarketSnapshot(chain="arbitrum", wallet_address="0xabc", gateway_client=None)
        assert market._gateway_client is None

    def test_init_stores_gateway_client(self):
        sentinel = object()
        market = MarketSnapshot(chain="arbitrum", wallet_address="0xabc", gateway_client=sentinel)
        assert market._gateway_client is sentinel


class TestPositionHealthCacheHit:
    def test_set_then_get_returns_cached_value(self):
        market = MarketSnapshot(chain="arbitrum", wallet_address="0xabc")
        expected = _sample_health()
        market.set_position_health("aave_v3", "aave_v3", expected)

        result = market.position_health(protocol="aave_v3", market_id="aave_v3")
        assert result is expected
        assert result.health_factor == Decimal("1.85")

    def test_cache_hit_does_not_invoke_provider(self):
        market = MarketSnapshot(chain="arbitrum", wallet_address="0xabc")
        market.set_position_health("aave_v3", "aave_v3", _sample_health())

        with patch("almanak.framework.data.position_health.PositionHealthProvider") as mock_provider:
            market.position_health(protocol="aave_v3", market_id="aave_v3")
            mock_provider.assert_not_called()

    def test_lending_loop_template_call_shape_works(self):
        # Exact call shape used by the lending_loop template at
        # almanak/framework/cli/new_strategy.py:473.
        market = MarketSnapshot(chain="arbitrum", wallet_address="0xabc")
        market.set_position_health("aave_v3", "aave_v3", _sample_health())

        hf_health = market.position_health(
            protocol="aave_v3",
            market_id="aave_v3",
        )
        assert hf_health.health_factor == Decimal("1.85")
        assert hf_health.debt_value_usd == Decimal("400")


class TestPositionHealthProviderInvocation:
    def test_provider_is_constructed_with_gateway_client(self):
        sentinel_gw = object()
        market = MarketSnapshot(
            chain="arbitrum",
            wallet_address="0xabc",
            gateway_client=sentinel_gw,
        )

        with patch("almanak.framework.data.position_health.PositionHealthProvider") as mock_cls:
            mock_cls.return_value.get_health.return_value = _sample_health()
            market.position_health(protocol="aave_v3", market_id="aave_v3")

        mock_cls.assert_called_once()
        kwargs = mock_cls.call_args.kwargs
        assert kwargs["gateway_client"] is sentinel_gw
        assert kwargs["chain"] == "arbitrum"

    def test_get_health_called_with_user_address(self):
        market = MarketSnapshot(chain="arbitrum", wallet_address="0xWALLET")

        with patch("almanak.framework.data.position_health.PositionHealthProvider") as mock_cls:
            mock_cls.return_value.get_health.return_value = _sample_health()
            market.position_health(protocol="aave_v3", market_id="aave_v3")

        get_health_kwargs = mock_cls.return_value.get_health.call_args.kwargs
        assert get_health_kwargs["protocol"] == "aave_v3"
        assert get_health_kwargs["market_id"] == "aave_v3"
        assert get_health_kwargs["user_address"] == "0xWALLET"

    def test_provider_failure_raises_health_unavailable(self):
        from almanak.framework.market import HealthUnavailableError

        market = MarketSnapshot(chain="arbitrum", wallet_address="0xabc")
        with patch("almanak.framework.data.position_health.PositionHealthProvider") as mock_cls:
            mock_cls.return_value.get_health.side_effect = RuntimeError("rpc failed")
            with pytest.raises(HealthUnavailableError):
                market.position_health(protocol="aave_v3", market_id="aave_v3")

    def test_disconnected_gateway_client_fails_fast(self):
        # Regression guard for PR #1926 review: a present-but-disconnected
        # gateway client must raise before any RPC attempt, with a clear message.
        from almanak.framework.market import HealthUnavailableError
        from almanak.framework.data.position_health import PositionHealthProvider

        disconnected = MagicMock(spec=["is_connected"])
        disconnected.is_connected = False

        provider = PositionHealthProvider(chain="arbitrum", gateway_client=disconnected)
        with pytest.raises(ValueError, match="not connected"):
            provider._get_aave_health(market_id="aave_v3", user_address="0x" + "1" * 40)

        market = MarketSnapshot(chain="arbitrum", wallet_address="0xabc", gateway_client=disconnected)
        with pytest.raises(HealthUnavailableError):
            market.position_health(protocol="aave_v3", market_id="aave_v3")

    def test_result_is_cached_after_first_call(self):
        market = MarketSnapshot(chain="arbitrum", wallet_address="0xabc")
        with patch("almanak.framework.data.position_health.PositionHealthProvider") as mock_cls:
            mock_cls.return_value.get_health.return_value = _sample_health()
            market.position_health(protocol="aave_v3", market_id="aave_v3")
            market.position_health(protocol="aave_v3", market_id="aave_v3")

        # The cache lookup happens before the provider is constructed, so on the
        # second call we return early — provider is built once, get_health runs once.
        assert mock_cls.call_count == 1
        assert mock_cls.return_value.get_health.call_count == 1
