"""Unit tests for MarketSnapshot.position_health() on the strategy-layer shim.

These tests guard against the regression where the shim diverged from the
data-layer canonical and templates generated by `almanak strat new --template
lending_loop` raised AttributeError on `market.position_health(...)` every
iteration after the first.
"""

from decimal import Decimal
from unittest.mock import MagicMock, patch

import pytest

from almanak.framework.data.position_health import PositionHealth
from almanak.framework.market import MarketSnapshot


def _sample_health() -> PositionHealth:
    return PositionHealth(
        health_factor=Decimal("1.85"),
        collateral_value_usd=Decimal("1000"),
        debt_value_usd=Decimal("400"),
        lltv=Decimal("0.85"),
        max_borrow_usd=Decimal("450"),
        protocol="aave_v3",
        market_id="aave_v3",
    )


class TestPositionHealthAttributeExists:
    def test_class_has_position_health(self):
        # Regression guard for the user's deployed agent bug:
        # `'MarketSnapshot' object has no attribute 'position_health'`.
        assert hasattr(MarketSnapshot, "position_health")

    def test_class_has_set_position_health(self):
        assert hasattr(MarketSnapshot, "set_position_health")

    def test_init_accepts_gateway_client(self):
        market = MarketSnapshot(chain="arbitrum", wallet_address="0xabc", gateway_client=None)
        assert market._gateway_client is None

    def test_init_stores_gateway_client(self):
        sentinel = object()
        market = MarketSnapshot(chain="arbitrum", wallet_address="0xabc", gateway_client=sentinel)
        assert market._gateway_client is sentinel


class TestPositionHealthCacheHit:
    def test_set_then_get_returns_cached_value(self):
        market = MarketSnapshot(chain="arbitrum", wallet_address="0xabc")
        expected = _sample_health()
        market.set_position_health("aave_v3", "aave_v3", expected)

        result = market.position_health(protocol="aave_v3", market_id="aave_v3")
        assert result is expected
        assert result.health_factor == Decimal("1.85")

    def test_cache_hit_does_not_invoke_provider(self):
        market = MarketSnapshot(chain="arbitrum", wallet_address="0xabc")
        market.set_position_health("aave_v3", "aave_v3", _sample_health())

        with patch("almanak.framework.data.position_health.PositionHealthProvider") as mock_provider:
            market.position_health(protocol="aave_v3", market_id="aave_v3")
            mock_provider.assert_not_called()

    def test_lending_loop_template_call_shape_works(self):
        # Exact call shape used by the lending_loop template at
        # almanak/framework/cli/new_strategy.py:473.
        market = MarketSnapshot(chain="arbitrum", wallet_address="0xabc")
        market.set_position_health("aave_v3", "aave_v3", _sample_health())

        hf_health = market.position_health(
            protocol="aave_v3",
            market_id="aave_v3",
        )
        assert hf_health.health_factor == Decimal("1.85")
        assert hf_health.debt_value_usd == Decimal("400")


class TestPositionHealthProviderInvocation:
    def test_provider_is_constructed_with_gateway_client(self):
        sentinel_gw = object()
        market = MarketSnapshot(
            chain="arbitrum",
            wallet_address="0xabc",
            gateway_client=sentinel_gw,
        )

        with patch("almanak.framework.data.position_health.PositionHealthProvider") as mock_cls:
            mock_cls.return_value.get_health.return_value = _sample_health()
            market.position_health(protocol="aave_v3", market_id="aave_v3")

        mock_cls.assert_called_once()
        kwargs = mock_cls.call_args.kwargs
        assert kwargs["gateway_client"] is sentinel_gw
        assert kwargs["chain"] == "arbitrum"

    def test_get_health_called_with_user_address(self):
        market = MarketSnapshot(chain="arbitrum", wallet_address="0xWALLET")

        with patch("almanak.framework.data.position_health.PositionHealthProvider") as mock_cls:
            mock_cls.return_value.get_health.return_value = _sample_health()
            market.position_health(protocol="aave_v3", market_id="aave_v3")

        get_health_kwargs = mock_cls.return_value.get_health.call_args.kwargs
        assert get_health_kwargs["protocol"] == "aave_v3"
        assert get_health_kwargs["market_id"] == "aave_v3"
        assert get_health_kwargs["user_address"] == "0xWALLET"

    def test_provider_failure_raises_health_unavailable(self):
        from almanak.framework.market import HealthUnavailableError

        market = MarketSnapshot(chain="arbitrum", wallet_address="0xabc")
        with patch("almanak.framework.data.position_health.PositionHealthProvider") as mock_cls:
            mock_cls.return_value.get_health.side_effect = RuntimeError("rpc failed")
            with pytest.raises(HealthUnavailableError):
                market.position_health(protocol="aave_v3", market_id="aave_v3")

    def test_disconnected_gateway_client_fails_fast(self):
        # Regression guard for PR #1926 review: a present-but-disconnected
        # gateway client must raise before any RPC attempt, with a clear message.
        from almanak.framework.market import HealthUnavailableError
        from almanak.framework.data.position_health import PositionHealthProvider

        disconnected = MagicMock(spec=["is_connected"])
        disconnected.is_connected = False

        # VIB-4851: the disconnected-fails-fast guard now lives in the public
        # ``get_health`` (the Aave arm routes through the lending-read seam, which
        # requires a connected gateway) -- ``_get_aave_health`` was deleted. The
        # behaviour is identical: a present-but-disconnected client raises
        # "not connected" before any RPC attempt.
        provider = PositionHealthProvider(chain="arbitrum", gateway_client=disconnected)
        with pytest.raises(ValueError, match="not connected"):
            provider.get_health("aave_v3", "aave_v3", "0x" + "1" * 40)

        market = MarketSnapshot(chain="arbitrum", wallet_address="0xabc", gateway_client=disconnected)
        with pytest.raises(HealthUnavailableError):
            market.position_health(protocol="aave_v3", market_id="aave_v3")

    def test_result_is_cached_after_first_call(self):
        market = MarketSnapshot(chain="arbitrum", wallet_address="0xabc")
        with patch("almanak.framework.data.position_health.PositionHealthProvider") as mock_cls:
            mock_cls.return_value.get_health.return_value = _sample_health()
            market.position_health(protocol="aave_v3", market_id="aave_v3")
            market.position_health(protocol="aave_v3", market_id="aave_v3")

        # The cache lookup happens before the provider is constructed, so on the
        # second call we return early — provider is built once, get_health runs once.
        assert mock_cls.call_count == 1
        assert mock_cls.return_value.get_health.call_count == 1


class TestInvalidatePositionHealth:
    """VIB-5523: teardown verification reuses a snapshot to confirm post-closure
    state; the per-(protocol, market_id, …) memo must be evictable so the post
    read re-queries the chain instead of serving the pre-unwind value."""

    def test_invalidate_all_clears_memo(self):
        market = MarketSnapshot(chain="arbitrum", wallet_address="0xabc")
        market.set_position_health("aave_v3", "wsteth", _sample_health())
        market.set_position_health("aave_v3", "usdc", _sample_health())
        assert market._position_health_cache

        market.invalidate_position_health()
        assert market._position_health_cache == {}

    def test_invalidate_targeted_protocol_market(self):
        market = MarketSnapshot(chain="arbitrum", wallet_address="0xabc")
        market.set_position_health("aave_v3", "wsteth", _sample_health())
        market.set_position_health("aave_v3", "usdc", _sample_health())

        market.invalidate_position_health("aave_v3", "wsteth")

        remaining = list(market._position_health_cache)
        assert ("aave_v3", "wsteth", "", "", "") not in remaining
        assert ("aave_v3", "usdc", "", "", "") in remaining

    def test_invalidate_is_case_insensitive(self):
        # Gemini MEDIUM (PR #3102): the cache is seeded with the raw casing the
        # caller passed; an invalidation arg whose casing differs (mixed-case
        # protocol slug, checksummed vs lowercase hex market_id) must still hit,
        # else the stale memo survives and defeats the VIB-5523 fix.
        market = MarketSnapshot(chain="arbitrum", wallet_address="0xabc")
        market.set_position_health("Aave_V3", "0xAbCdEf", _sample_health())
        market.set_position_health("aave_v3", "usdc", _sample_health())

        # Invalidate with lowercase args though the key was seeded mixed-case.
        market.invalidate_position_health("aave_v3", "0xabcdef")

        remaining = list(market._position_health_cache)
        assert ("Aave_V3", "0xAbCdEf", "", "", "") not in remaining
        assert ("aave_v3", "usdc", "", "", "") in remaining

    def test_invalidate_non_string_market_id_does_not_raise(self):
        # CodeRabbit MAJOR (PR #3102): non-string identifiers — an int ``0`` or a
        # bytes32/int Morpho market id — must not raise AttributeError in
        # invalidate_position_health. A bare ``market_id.lower()`` crashed for
        # exactly the falsy non-string edge case this PR targets, so eviction
        # never reached the matching entry. Seed with an int market_id and
        # evict with the same int; the matching key must be removed and the
        # sibling preserved.
        market = MarketSnapshot(chain="arbitrum", wallet_address="0xabc")
        market._position_health_cache[("morpho_blue", 0, "", "", "")] = _sample_health()
        market._position_health_cache[("morpho_blue", 1, "", "", "")] = _sample_health()

        # Pre-fix this raised AttributeError: 'int' object has no attribute 'lower'.
        market.invalidate_position_health("morpho_blue", 0)

        remaining = list(market._position_health_cache)
        assert ("morpho_blue", 0, "", "", "") not in remaining
        assert ("morpho_blue", 1, "", "", "") in remaining

    def test_invalidate_then_get_re_reads_provider(self):
        market = MarketSnapshot(chain="arbitrum", wallet_address="0xabc")
        with patch("almanak.framework.data.position_health.PositionHealthProvider") as mock_cls:
            mock_cls.return_value.get_health.return_value = _sample_health()
            market.position_health(protocol="aave_v3", market_id="aave_v3")
            market.invalidate_position_health()
            market.position_health(protocol="aave_v3", market_id="aave_v3")

        # Eviction forces a second provider read (vs the cache-hit test above).
        assert mock_cls.return_value.get_health.call_count == 2


class TestMorphoCrossAssetDefaultPricing:
    """Regression: ``market.position_health("morpho_blue", ...)``
    must return a numeric HF for a catalogued cross-asset market WITHOUT the
    strategy injecting price overrides.

    Reconstructs the morpho lifecycle failure end-to-end against the
    REAL Ethereum wstETH/USDC ``MORPHO_MARKETS`` catalogue entry and the real
    seam (registry -> account-state spec -> reducer). The ONLY fake is the
    gateway, which scripts the three chain reads: the market's own
    ``IOracle.price()``, Morpho ``position(id, user)``, and ``market(id)``.
    Pre-fix this exact call raised ``HealthUnavailableError("... Price
    overrides required for cross-asset morpho_blue market ...")`` on EVERY
    catalogued market (they are all cross-asset), making the read unusable by
    default (ALM-2895 HOLD loop; VIB-5527 gated only pre-deploy coverage).
    """

    # Real Ethereum wstETH/USDC market (86% LLTV) + its catalogue oracle.
    _MARKET_ID = "0xb323495f7e4148be5643a4ea4a8221eef163e4bccfdedc2a6f4696baacbc86cc"
    _ORACLE = "0x48F7E36EB6B826B2dF4B2E630B62Cd25e89E40e2"
    _PRICE_SELECTOR = "0xa035b1fe"
    _POSITION_SELECTOR = "0x93c52062"
    _MARKET_SELECTOR = "0x5c60e39a"

    def _scripted_gateway(self) -> MagicMock:
        word = lambda v: format(v, "064x")  # noqa: E731
        # 2 wstETH collateral; 3000 USDC debt (shares 1:1); price 3000 USDC/wstETH.
        position_blob = "0x" + word(0) + word(3000 * 10**6) + word(2 * 10**18)
        market_blob = "0x" + "".join(word(w) for w in (0, 0, 10_000 * 10**6, 10_000 * 10**6, 0, 0))
        price_blob = "0x" + word(3000 * 10**24)

        def _eth_call(chain: str, to: str, data: str, block=None) -> str:
            assert chain == "ethereum"
            if data.startswith(self._PRICE_SELECTOR):
                assert to.lower() == self._ORACLE.lower()  # the catalogue oracle
                return price_blob
            if data.startswith(self._POSITION_SELECTOR):
                return position_blob
            if data.startswith(self._MARKET_SELECTOR):
                return market_blob
            raise AssertionError(f"unexpected selector: {data[:10]}")

        gateway = MagicMock()
        gateway.is_connected = True
        gateway.eth_call = _eth_call
        return gateway

    def test_audit_scenario_numeric_hf_without_overrides(self):
        from almanak.framework.data.position_health import PRICE_SOURCE_MARKET_ORACLE

        market = MarketSnapshot(
            chain="ethereum",
            wallet_address="0xABCDEF0123456789abcdef0123456789ABCDEF01",
            gateway_client=self._scripted_gateway(),
        )

        # Pre-fix: HealthUnavailableError("Position health unavailable: Price
        # overrides required for cross-asset morpho_blue market ...").
        health = market.position_health(protocol="morpho_blue", market_id=self._MARKET_ID)

        # HF = (2 * 3000 * 0.86) / 3000 = 1.72 exactly (86% catalogue LLTV).
        assert health.health_factor == Decimal("1.72")
        assert health.collateral_value_usd == Decimal("6000")
        assert health.debt_value_usd == Decimal("3000")
        # Provenance: oracle-defaulted, distinguishable from override-computed.
        assert health.price_source == PRICE_SOURCE_MARKET_ORACLE


class TestVIB5775CacheKeyOnResolvedMarketId:
    """VIB-5775: an empty-``market_id`` + typed ``ref`` call must key the cache on
    the RESOLVED synthetic id, so it (a) HITS a ``set_position_health`` pre-seed on
    that id (set/get symmetry) and (b) does NOT collide across distinct positions."""

    @staticmethod
    def _euler_ref(collateral: str):
        from almanak.connectors._strategy_base.lending_read_base import LendingPositionRef

        # euler intents carry no market_id; the ref names the tokens. ethereum has
        # single-leg "usdc" and "weth" catalogue entries.
        return LendingPositionRef(protocol="euler_v2", chain="ethereum", collateral_token=collateral, loan_token=None)

    def _health(self, hf: str) -> PositionHealth:
        return PositionHealth(
            health_factor=Decimal(hf),
            collateral_value_usd=Decimal("500"),
            debt_value_usd=Decimal("0"),
            lltv=Decimal("0"),
            max_borrow_usd=Decimal("0"),
            protocol="euler_v2",
            market_id="usdc",
        )

    def test_empty_market_id_plus_ref_hits_preseed_on_resolved_id(self):
        market = MarketSnapshot(chain="ethereum", wallet_address="0xabc")
        seeded = self._health("111")
        # Strategy pre-seeds under the explicit short key the resolver produces.
        market.set_position_health("euler_v2", "usdc", seeded)

        # Empty market_id + euler USDC ref → resolves "usdc" → HITS the pre-seed,
        # WITHOUT invoking the provider (no gateway needed).
        with patch("almanak.framework.data.position_health.PositionHealthProvider") as mock_provider:
            result = market.position_health(protocol="euler_v2", market_id="", ref=self._euler_ref("USDC"))
            mock_provider.assert_not_called()
        assert result is seeded

    def test_distinct_euler_refs_do_not_collide(self):
        market = MarketSnapshot(chain="ethereum", wallet_address="0xabc")
        usdc_health = self._health("111")
        weth_health = self._health("222")
        market.set_position_health("euler_v2", "usdc", usdc_health)
        market.set_position_health("euler_v2", "weth", weth_health)

        with patch("almanak.framework.data.position_health.PositionHealthProvider") as mock_provider:
            got_usdc = market.position_health(protocol="euler_v2", market_id="", ref=self._euler_ref("USDC"))
            got_weth = market.position_health(protocol="euler_v2", market_id="", ref=self._euler_ref("WETH"))
            mock_provider.assert_not_called()
        # Each ref resolves to its OWN id → no cross-position collision.
        assert got_usdc is usdc_health
        assert got_weth is weth_health
        assert got_usdc is not got_weth
