"""Monte Carlo simulation runner for backtesting.

This module provides functionality to run backtests across multiple simulated
price paths generated by the MonteCarloPathGenerator. It enables statistical
analysis of strategy performance across many possible market scenarios.

Key Components:
    - MonteCarloConfig: Configuration for Monte Carlo simulation
    - MonteCarloPathResult: Result from a single path backtest
    - MonteCarloSimulationResult: Aggregated results from all paths
    - SimulatedPricePathProvider: Data provider using simulated paths
    - run_monte_carlo: Main function to run Monte Carlo backtests

Example:
    from almanak.framework.backtesting.pnl.calculators.monte_carlo import (
        MonteCarloPathGenerator,
    )
    from almanak.framework.backtesting.pnl.calculators.monte_carlo_runner import (
        MonteCarloConfig,
        run_monte_carlo,
    )

    # Generate price paths
    generator = MonteCarloPathGenerator()
    paths = generator.generate_price_paths(historical_prices, n_paths=1000)

    # Configure and run simulation
    mc_config = MonteCarloConfig(n_paths=1000)
    result = await run_monte_carlo(strategy, paths, backtest_config, mc_config)

    # Analyze results
    print(f"95% CI: [{result.return_percentile_5th}, {result.return_percentile_95th}]")
"""

import asyncio
import logging
from collections.abc import AsyncIterator
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from decimal import Decimal
from typing import Any

from almanak.core.chains import DEFAULT_CHAIN
from almanak.framework.backtesting.models import BacktestMetrics, BacktestResult
from almanak.framework.backtesting.pnl.calculators._monte_carlo_helpers import (
    _calculate_percentile as _helper_percentile,
)
from almanak.framework.backtesting.pnl.calculators._monte_carlo_helpers import (
    _calculate_std as _helper_std,
)
from almanak.framework.backtesting.pnl.calculators._monte_carlo_helpers import (
    aggregate_successful_results,
    build_empty_result,
    determine_paths_to_run,
    dispatch_backtests,
    resolve_runtime_defaults,
)
from almanak.framework.backtesting.pnl.calculators.monte_carlo import PricePathResult
from almanak.framework.backtesting.pnl.config import PnLBacktestConfig
from almanak.framework.backtesting.pnl.data_provider import (
    HistoricalDataConfig,
    MarketState,
    TokenRef,
)

logger = logging.getLogger(__name__)


@dataclass
class MonteCarloConfig:
    """Configuration for Monte Carlo simulation.

    Attributes:
        n_paths: Number of paths to simulate (default: 1000).
            If PricePathResult has fewer paths, only available paths are used.
        parallel_workers: Number of parallel workers for backtest execution (default: 4).
            Set to 1 for sequential execution.
        base_token: Primary token being simulated (default: 'WETH').
            Other tokens use the simulated paths or stable pricing.
        quote_token: Quote token for stable pricing (default: 'USDC').
            Assumed to be $1.00 throughout simulation.
        seed: Random seed for reproducibility in path selection (default: None).
        collect_individual_results: Whether to store individual path results (default: True).
            Set to False to save memory when only aggregates are needed.
        progress_callback: Optional callback for progress updates.
            Called with (completed_paths, total_paths) after each backtest.
        drawdown_thresholds: List of drawdown thresholds to calculate probabilities for.
            Default: [0.05, 0.10, 0.15, 0.20, 0.25, 0.30] (5%, 10%, 15%, 20%, 25%, 30%).
    """

    n_paths: int = 1000
    parallel_workers: int = 4
    base_token: str = "WETH"
    quote_token: str = "USDC"
    seed: int | None = None
    collect_individual_results: bool = True
    progress_callback: Any | None = None  # Callable[[int, int], None]
    drawdown_thresholds: list[Decimal] = field(
        default_factory=lambda: [
            Decimal("0.05"),
            Decimal("0.10"),
            Decimal("0.15"),
            Decimal("0.20"),
            Decimal("0.25"),
            Decimal("0.30"),
        ]
    )

    def __post_init__(self) -> None:
        """Validate configuration."""
        if self.n_paths <= 0:
            raise ValueError("n_paths must be positive")
        if self.parallel_workers <= 0:
            raise ValueError("parallel_workers must be positive")
        # Validate drawdown thresholds
        for threshold in self.drawdown_thresholds:
            if threshold < 0 or threshold > 1:
                raise ValueError(f"Drawdown threshold must be between 0 and 1, got {threshold}")

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "n_paths": self.n_paths,
            "parallel_workers": self.parallel_workers,
            "base_token": self.base_token,
            "quote_token": self.quote_token,
            "seed": self.seed,
            "collect_individual_results": self.collect_individual_results,
            "drawdown_thresholds": [str(t) for t in self.drawdown_thresholds],
        }


@dataclass
class MonteCarloPathBacktestResult:
    """Result from a single path backtest.

    Attributes:
        path_index: Index of the simulated path (0 to n_paths-1)
        final_return: Total return (final - initial) / initial
        final_value_usd: Final portfolio value in USD
        max_drawdown: Maximum drawdown during the simulation
        sharpe_ratio: Sharpe ratio for this path (if calculable)
        total_trades: Number of trades executed
        metrics: Full backtest metrics (optional, for detailed analysis)
        success: Whether the backtest completed successfully
        error: Error message if backtest failed
    """

    path_index: int
    final_return: Decimal
    final_value_usd: Decimal
    max_drawdown: Decimal
    sharpe_ratio: Decimal | None = None
    total_trades: int = 0
    metrics: BacktestMetrics | None = None
    success: bool = True
    error: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "path_index": self.path_index,
            "final_return": str(self.final_return),
            "final_value_usd": str(self.final_value_usd),
            "max_drawdown": str(self.max_drawdown),
            "sharpe_ratio": str(self.sharpe_ratio) if self.sharpe_ratio else None,
            "total_trades": self.total_trades,
            "success": self.success,
            "error": self.error,
        }


@dataclass
class MonteCarloSimulationResult:
    """Aggregated results from Monte Carlo simulation.

    Contains statistical summaries across all simulated paths, including
    confidence intervals, probabilities, and distribution metrics.

    Attributes:
        n_paths: Number of paths that were simulated
        n_successful: Number of paths that completed successfully
        n_failed: Number of paths that failed

        return_mean: Mean final return across all paths
        return_std: Standard deviation of final returns
        return_percentile_5th: 5th percentile of returns (worst case)
        return_percentile_25th: 25th percentile of returns
        return_percentile_50th: 50th percentile (median) of returns
        return_percentile_75th: 75th percentile of returns
        return_percentile_95th: 95th percentile of returns (best case)

        max_drawdown_mean: Mean max drawdown across paths
        max_drawdown_worst: Worst (largest) max drawdown observed
        max_drawdown_percentile_95th: 95th percentile of max drawdowns

        probability_negative_return: Probability of negative return
        probability_loss_exceeds_10pct: Probability of >10% loss
        probability_loss_exceeds_20pct: Probability of >20% loss
        probability_gain_exceeds_10pct: Probability of >10% gain
        probability_drawdown_exceeds_threshold: Dict mapping threshold (e.g., "0.10") to
            probability that max drawdown exceeds that threshold. Standard thresholds
            include 5%, 10%, 15%, 20%, 25%, 30%.

        sharpe_mean: Mean Sharpe ratio (excluding None values)
        sharpe_std: Standard deviation of Sharpe ratios

        individual_results: List of results per path (if collected)
        price_paths_config: Configuration of the price paths used
        monte_carlo_config: Monte Carlo simulation configuration
    """

    n_paths: int
    n_successful: int
    n_failed: int

    # Return statistics
    return_mean: Decimal
    return_std: Decimal
    return_percentile_5th: Decimal
    return_percentile_25th: Decimal
    return_percentile_50th: Decimal
    return_percentile_75th: Decimal
    return_percentile_95th: Decimal

    # Drawdown statistics
    max_drawdown_mean: Decimal
    max_drawdown_worst: Decimal
    max_drawdown_percentile_95th: Decimal

    # Probabilities
    probability_negative_return: Decimal
    probability_loss_exceeds_10pct: Decimal
    probability_loss_exceeds_20pct: Decimal
    probability_gain_exceeds_10pct: Decimal
    probability_drawdown_exceeds_threshold: dict[str, Decimal] = field(default_factory=dict)

    # Sharpe ratio statistics
    sharpe_mean: Decimal | None = None
    sharpe_std: Decimal | None = None

    # Individual results
    individual_results: list[MonteCarloPathBacktestResult] = field(default_factory=list)

    # Configuration used
    price_paths_config: dict[str, Any] = field(default_factory=dict)
    monte_carlo_config: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "n_paths": self.n_paths,
            "n_successful": self.n_successful,
            "n_failed": self.n_failed,
            "return_mean": str(self.return_mean),
            "return_std": str(self.return_std),
            "return_percentile_5th": str(self.return_percentile_5th),
            "return_percentile_25th": str(self.return_percentile_25th),
            "return_percentile_50th": str(self.return_percentile_50th),
            "return_percentile_75th": str(self.return_percentile_75th),
            "return_percentile_95th": str(self.return_percentile_95th),
            "max_drawdown_mean": str(self.max_drawdown_mean),
            "max_drawdown_worst": str(self.max_drawdown_worst),
            "max_drawdown_percentile_95th": str(self.max_drawdown_percentile_95th),
            "probability_negative_return": str(self.probability_negative_return),
            "probability_loss_exceeds_10pct": str(self.probability_loss_exceeds_10pct),
            "probability_loss_exceeds_20pct": str(self.probability_loss_exceeds_20pct),
            "probability_gain_exceeds_10pct": str(self.probability_gain_exceeds_10pct),
            "probability_drawdown_exceeds_threshold": {
                k: str(v) for k, v in self.probability_drawdown_exceeds_threshold.items()
            },
            "sharpe_mean": str(self.sharpe_mean) if self.sharpe_mean else None,
            "sharpe_std": str(self.sharpe_std) if self.sharpe_std else None,
            "individual_results": [r.to_dict() for r in self.individual_results],
            "price_paths_config": self.price_paths_config,
            "monte_carlo_config": self.monte_carlo_config,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "MonteCarloSimulationResult":
        """Deserialize from dictionary."""
        return cls(
            n_paths=data["n_paths"],
            n_successful=data["n_successful"],
            n_failed=data["n_failed"],
            return_mean=Decimal(data["return_mean"]),
            return_std=Decimal(data["return_std"]),
            return_percentile_5th=Decimal(data["return_percentile_5th"]),
            return_percentile_25th=Decimal(data["return_percentile_25th"]),
            return_percentile_50th=Decimal(data["return_percentile_50th"]),
            return_percentile_75th=Decimal(data["return_percentile_75th"]),
            return_percentile_95th=Decimal(data["return_percentile_95th"]),
            max_drawdown_mean=Decimal(data["max_drawdown_mean"]),
            max_drawdown_worst=Decimal(data["max_drawdown_worst"]),
            max_drawdown_percentile_95th=Decimal(data["max_drawdown_percentile_95th"]),
            probability_negative_return=Decimal(data["probability_negative_return"]),
            probability_loss_exceeds_10pct=Decimal(data["probability_loss_exceeds_10pct"]),
            probability_loss_exceeds_20pct=Decimal(data["probability_loss_exceeds_20pct"]),
            probability_gain_exceeds_10pct=Decimal(data["probability_gain_exceeds_10pct"]),
            probability_drawdown_exceeds_threshold={
                k: Decimal(v) for k, v in data.get("probability_drawdown_exceeds_threshold", {}).items()
            },
            sharpe_mean=Decimal(data["sharpe_mean"]) if data.get("sharpe_mean") else None,
            sharpe_std=Decimal(data["sharpe_std"]) if data.get("sharpe_std") else None,
            price_paths_config=data.get("price_paths_config", {}),
            monte_carlo_config=data.get("monte_carlo_config", {}),
            # Skip deserializing individual_results for now (large)
            individual_results=[],
        )


class SimulatedPricePathProvider:
    """Data provider that uses a simulated price path.

    This provider implements the HistoricalDataProvider protocol using
    a pre-generated price path from Monte Carlo simulation.

    Attributes:
        price_path: List of prices for each time step
        base_token: Token symbol for the simulated prices (e.g., 'WETH')
        quote_token: Quote token assumed to be $1.00 (e.g., 'USDC')
        start_time: Start time for the simulation
        interval_seconds: Time between price points in seconds
    """

    def __init__(
        self,
        price_path: list[Decimal],
        base_token: str = "WETH",
        quote_token: str = "USDC",
        start_time: datetime | None = None,
        interval_seconds: int = 3600,
    ) -> None:
        """Initialize the simulated price path provider.

        Args:
            price_path: List of prices for each time step
            base_token: Token symbol for the simulated prices
            quote_token: Quote token (assumed $1.00)
            start_time: Start time for the simulation (default: now)
            interval_seconds: Time between price points in seconds
        """
        self.price_path = price_path
        self.base_token = base_token.upper()
        self.quote_token = quote_token.upper()
        self.start_time = start_time or datetime.now()
        self.interval_seconds = interval_seconds

    async def get_price(self, token: str, timestamp: datetime) -> Decimal:
        """Get the price of a token at a specific timestamp.

        Args:
            token: Token symbol
            timestamp: The point in time

        Returns:
            Price in USD
        """
        token_upper = token.upper()

        # Quote token is always $1.00
        if token_upper == self.quote_token:
            return Decimal("1")

        # For base token, find the closest price from the path
        if token_upper == self.base_token:
            delta = timestamp - self.start_time
            step_index = int(delta.total_seconds() // self.interval_seconds)
            step_index = max(0, min(step_index, len(self.price_path) - 1))
            return self.price_path[step_index]

        # Unknown token - return placeholder
        raise ValueError(f"Price not available for token: {token}")

    async def get_ohlcv(
        self,
        token: str,
        start: datetime,
        end: datetime,
        interval: int,
    ) -> list[Any]:
        """Get OHLCV data (simplified for simulation)."""
        return []

    async def iterate(self, config: HistoricalDataConfig) -> AsyncIterator[tuple[datetime, MarketState]]:
        """Iterate through market states for backtesting.

        Args:
            config: Data retrieval configuration

        Yields:
            Tuples of (timestamp, MarketState) for each time step
        """
        current_time = config.start_time
        step = 0

        while current_time <= config.end_time and step < len(self.price_path):
            # Get price for this step
            price = self.price_path[step]

            # Build prices dict
            prices: dict[TokenRef, Decimal] = {
                self.base_token: price,
                self.quote_token: Decimal("1"),
            }

            # Create market state
            market_state = MarketState(
                timestamp=current_time,
                prices=prices,
                chain=config.chains[0] if config.chains else DEFAULT_CHAIN,
            )

            yield current_time, market_state

            # Advance time
            current_time = current_time + timedelta(seconds=config.interval_seconds)
            step += 1


async def _run_single_path_backtest(
    strategy: Any,
    price_path: list[Decimal],
    backtest_config: PnLBacktestConfig,
    mc_config: MonteCarloConfig,
    path_index: int,
    backtester_class: type,
    fee_models: dict[str, Any],
    slippage_models: dict[str, Any],
) -> MonteCarloPathBacktestResult:
    """Run a backtest on a single price path.

    Args:
        strategy: Strategy to backtest
        price_path: Simulated price path
        backtest_config: Backtest configuration
        mc_config: Monte Carlo configuration
        path_index: Index of this path
        backtester_class: PnLBacktester class to use
        fee_models: Fee models for backtester
        slippage_models: Slippage models for backtester

    Returns:
        MonteCarloPathBacktestResult with results from this path
    """
    try:
        # Create data provider for this path
        data_provider = SimulatedPricePathProvider(
            price_path=price_path,
            base_token=mc_config.base_token,
            quote_token=mc_config.quote_token,
            start_time=backtest_config.start_time,
            interval_seconds=backtest_config.interval_seconds,
        )

        # Create backtester
        backtester = backtester_class(
            data_provider=data_provider,
            fee_models=fee_models,
            slippage_models=slippage_models,
        )

        # Run backtest
        result: BacktestResult = await backtester.backtest(strategy, backtest_config)

        # Extract key metrics
        initial = result.initial_portfolio_value_usd or Decimal("0")
        final = result.final_capital_usd
        final_return = (final - initial) / initial if initial > 0 else Decimal("0")

        return MonteCarloPathBacktestResult(
            path_index=path_index,
            final_return=final_return,
            final_value_usd=final,
            max_drawdown=result.metrics.max_drawdown_pct,
            sharpe_ratio=result.metrics.sharpe_ratio,
            total_trades=result.metrics.total_trades,
            metrics=result.metrics if mc_config.collect_individual_results else None,
            success=True,
        )

    except Exception as e:
        logger.warning(f"Path {path_index} backtest failed: {e}")
        return MonteCarloPathBacktestResult(
            path_index=path_index,
            final_return=Decimal("0"),
            final_value_usd=Decimal("0"),
            max_drawdown=Decimal("0"),
            success=False,
            error=str(e),
        )


def _calculate_percentile(values: list[Decimal], percentile: float) -> Decimal:
    """Calculate a percentile from a list of values.

    Thin wrapper kept for backward compatibility; delegates to
    :func:`almanak.framework.backtesting.pnl.calculators._monte_carlo_helpers._calculate_percentile`.

    Args:
        values: Sorted list of values
        percentile: Percentile (0-100)

    Returns:
        Value at the given percentile
    """
    return _helper_percentile(values, percentile)


def _calculate_std(values: list[Decimal], mean: Decimal) -> Decimal:
    """Calculate standard deviation.

    Thin wrapper kept for backward compatibility; delegates to
    :func:`almanak.framework.backtesting.pnl.calculators._monte_carlo_helpers._calculate_std`.

    Args:
        values: List of values
        mean: Mean of values

    Returns:
        Standard deviation
    """
    return _helper_std(values, mean)


async def run_monte_carlo(
    strategy: Any,
    paths: PricePathResult,
    backtest_config: PnLBacktestConfig,
    mc_config: MonteCarloConfig | None = None,
    fee_models: dict[str, Any] | None = None,
    slippage_models: dict[str, Any] | None = None,
) -> MonteCarloSimulationResult:
    """Run Monte Carlo simulation across multiple price paths.

    This is the main entry point for Monte Carlo backtesting. It runs the
    strategy across all simulated price paths and aggregates the results
    into statistical summaries.

    Args:
        strategy: Strategy to backtest (must implement BacktestableStrategy)
        paths: Price paths from MonteCarloPathGenerator
        backtest_config: Configuration for each backtest run
        mc_config: Monte Carlo simulation configuration (optional)
        fee_models: Fee models for backtester (optional, uses defaults)
        slippage_models: Slippage models for backtester (optional, uses defaults)

    Returns:
        MonteCarloSimulationResult with aggregated statistics

    Example:
        from almanak.framework.backtesting.pnl.calculators.monte_carlo import (
            MonteCarloPathGenerator,
        )

        generator = MonteCarloPathGenerator()
        paths = generator.generate_price_paths(historical_prices, n_paths=1000)

        result = await run_monte_carlo(
            strategy=my_strategy,
            paths=paths,
            backtest_config=config,
        )

        print(f"Mean return: {result.return_mean:.2%}")
        print(f"95% CI: [{result.return_percentile_5th:.2%}, {result.return_percentile_95th:.2%}]")
    """
    # Import here to avoid circular import
    from almanak.framework.backtesting.pnl.engine import PnLBacktester

    # Phase 1: resolve runtime defaults (mc_config / fee_models / slippage_models)
    mc_config, fee_models, slippage_models = resolve_runtime_defaults(mc_config, fee_models, slippage_models)

    # Phase 2: determine number of paths to run (with warning log if clamped).
    # Pass the runner logger so ``record.name`` matches the pre-refactor path
    # (preserves downstream log filters / alerts keyed to this module).
    n_paths_to_run = determine_paths_to_run(paths, mc_config.n_paths, logger_=logger)
    logger.info(f"Starting Monte Carlo simulation with {n_paths_to_run} paths")

    # Phase 3: dispatch per-path backtests (parallel or sequential).
    # The per-path runner is injected so tests and future variants can swap it.
    async def _run_path(path_idx: int) -> MonteCarloPathBacktestResult:
        return await _run_single_path_backtest(
            strategy=strategy,
            price_path=paths.paths[path_idx],
            backtest_config=backtest_config,
            mc_config=mc_config,
            path_index=path_idx,
            backtester_class=PnLBacktester,
            fee_models=fee_models,
            slippage_models=slippage_models,
        )

    results = await dispatch_backtests(
        n_paths_to_run=n_paths_to_run,
        parallel_workers=mc_config.parallel_workers,
        run_path=_run_path,
        progress_callback=mc_config.progress_callback,
    )

    # Partition successful / failed.
    successful_results = [r for r in results if r.success]
    n_successful = len(successful_results)
    n_failed = len(results) - n_successful
    logger.info(f"Monte Carlo complete: {n_successful} successful, {n_failed} failed")

    # Phase 4: all-failed early return.
    if n_successful == 0:
        return build_empty_result(
            n_paths_to_run=n_paths_to_run,
            n_failed=n_failed,
            results=results,
            mc_config=mc_config,
            paths=paths,
        )

    # Phase 5: aggregate successful results.
    return aggregate_successful_results(
        results=results,
        successful=successful_results,
        n_paths_to_run=n_paths_to_run,
        n_failed=n_failed,
        mc_config=mc_config,
        paths=paths,
    )


def run_monte_carlo_sync(
    strategy: Any,
    paths: PricePathResult,
    backtest_config: PnLBacktestConfig,
    mc_config: MonteCarloConfig | None = None,
    fee_models: dict[str, Any] | None = None,
    slippage_models: dict[str, Any] | None = None,
) -> MonteCarloSimulationResult:
    """Synchronous wrapper for run_monte_carlo.

    Args:
        strategy: Strategy to backtest
        paths: Price paths from MonteCarloPathGenerator
        backtest_config: Configuration for each backtest run
        mc_config: Monte Carlo simulation configuration (optional)
        fee_models: Fee models for backtester (optional)
        slippage_models: Slippage models for backtester (optional)

    Returns:
        MonteCarloSimulationResult with aggregated statistics
    """
    return asyncio.run(
        run_monte_carlo(
            strategy=strategy,
            paths=paths,
            backtest_config=backtest_config,
            mc_config=mc_config,
            fee_models=fee_models,
            slippage_models=slippage_models,
        )
    )


__all__ = [
    "MonteCarloConfig",
    "MonteCarloPathBacktestResult",
    "MonteCarloSimulationResult",
    "SimulatedPricePathProvider",
    "run_monte_carlo",
    "run_monte_carlo_sync",
]
