"""Almanak SDK public API.

Names listed in ``__all__`` are resolved lazily via :pep:`562` ``__getattr__`` so
that consumers (notably the gateway sidecar, where ``almanak.framework.*``
submodules pull in pandas / web3 / streamlit / matplotlib transitively) only pay
the import cost of subpackages they actually touch. The ``TYPE_CHECKING`` block
below preserves the eager re-exports for static type checkers (mypy, pyright)
and IDE autocomplete.
"""

from typing import TYPE_CHECKING

from ._version import __version__

if TYPE_CHECKING:
    from .core.enums import (
        ActionType,
        Chain,
        CoSigners,
        ExecutionStatus,
        Network,
        SwapSide,
        TransactionType,
    )
    from .framework import (
        DEFAULT_GAS_ESTIMATES,
        PROTOCOL_ROUTERS,
        STRATEGY_REGISTRY,
        ABTest,
        ABTestConfig,
        ABTestEventType,
        ABTestManager,
        ABTestResult,
        ABTestStatus,
        AggregatedPrice,
        AlertManager,
        AlertSendResult,
        AllowanceInfo,
        BacktestMetrics,
        BacktestResult,
        BalanceInfo,
        BalanceProvider,
        BorrowIntent,
        BorrowPosition,
        CanaryComparison,
        CanaryConfig,
        CanaryDecision,
        CanaryDeployment,
        CanaryEventType,
        CanaryMetrics,
        CanaryResult,
        CanaryState,
        CanaryStatus,
        CircuitBreaker,
        CollectFeesIntent,
        CompilationResult,
        CompilationStatus,
        ConfigSnapshot,
        ConfigValidationError,
        CooldownTracker,
        CreateTestResult,
        DataClassification,
        DataEnvelope,
        DataMeta,
        DataProvider,
        DataRouter,
        DataUnavailableError,
        DefaultSwapAdapter,
        DeployCanaryResult,
        EmergencyManager,
        EmergencyResult,
        EndTestResult,
        EscalationLevel,
        EscalationPolicy,
        EscalationResult,
        EscalationState,
        EscalationStatus,
        ExecutionResult,
        FullPositionSummary,
        GetPositionCallback,
        HoldIntent,
        ILExposureUnavailableError,
        Instrument,
        Intent,
        IntentCompiler,
        IntentCompilerConfig,
        IntentStrategy,
        IntentType,
        LiquidityDepth,
        LogFormat,
        LogLevel,
        LowConfidenceError,
        LPCloseIntent,
        LPOpenIntent,
        LPPositionInfo,
        MarketSnapshot,
        MarketSnapshotBuilder,
        MarketSnapshotError,
        MigrationError,
        MigrationNotFoundError,
        MigrationRegistry,
        MigrationResult,
        MultiChainMarketSnapshot,
        MultiStepStrategy,
        NotificationCallback,
        OperatorCardGenerator,
        PauseStrategyCallback,
        PendingTransaction,
        PoolAnalytics,
        PoolPrice,
        PoolSnapshot,
        PortfolioRisk,
        PostgresConfig,
        PriceData,
        PriceInfo,
        PriceOracle,
        PromotionCriteria,
        RepayIntent,
        RiskConventions,
        RiskGuard,
        RiskGuardConfig,
        RiskGuardGuidance,
        RiskGuardResult,
        RollbackInfo,
        RollbackNotSafeError,
        RSIData,
        RSIProvider,
        SlippageEstimate,
        StateConflictError,
        StateData,
        StatelessStrategy,
        StateManager,
        StateManagerConfig,
        StateMigration,
        StateNotFoundError,
        StateTier,
        StatisticalResult,
        StrategyBase,
        StrategyMetadata,
        StrategySnapshot,
        StuckDetectionResult,
        StuckDetector,
        SwapIntent,
        TierMetrics,
        TimelineEvent,
        TimelineEventType,
        TimelineResponse,
        TokenBalance,
        TokenInfo,
        TokenPosition,
        TradeRecord,
        TransactionData,
        VariantComparison,
        VariantMetrics,
        VaRMethod,
        VaultDepositIntent,
        VaultRedeemIntent,
        VolatilityResult,
        YieldOpportunity,
        add_context,
        almanak_strategy,
        auto_migrate,
        check_rollback_safety,
        clear_context,
        configure_logging,
        create_emergency_manager,
        get_logger,
        get_registry,
        get_rollback_safe_version,
        get_strategy,
        list_strategies,
        migrate,
        migrate_state_data,
        migration,
        needs_migration,
        new_strategy,
        register_migration,
        register_strategy,
        resolve_instrument,
        timeline_router,
        unregister_strategy,
    )

    # Backward compatibility alias - Strategy maps to IntentStrategy.
    Strategy = IntentStrategy

__all__ = [
    "__version__",
    # Framework - Enums
    "ActionType",
    "Chain",
    "CoSigners",
    "ExecutionStatus",
    "Network",
    "SwapSide",
    "TransactionType",
    # V2 Framework - Strategy base classes
    "Strategy",  # Alias for IntentStrategy
    "IntentStrategy",
    "StatelessStrategy",
    "MultiStepStrategy",
    "StrategyBase",
    "MarketSnapshot",
    "MultiChainMarketSnapshot",
    # MarketSnapshot typed errors (VIB-5153 / ALM-2814): exported top-level so
    # strategies can catch transient market-data failures by type rather than
    # relying on a bare ``except`` or accidentally letting them escape into a
    # circuit-breaker fast-fail.
    "MarketSnapshotError",
    "ILExposureUnavailableError",
    "TokenBalance",
    "PriceData",
    "RSIData",
    "PriceOracle",
    "RSIProvider",
    "BalanceProvider",
    "ExecutionResult",
    "almanak_strategy",
    "StrategyMetadata",
    # V2 Framework - Strategy registry
    "STRATEGY_REGISTRY",
    "get_strategy",
    "list_strategies",
    "register_strategy",
    "unregister_strategy",
    # V2 Framework - Config
    "ConfigSnapshot",
    "ConfigValidationError",
    "NotificationCallback",
    "RiskGuard",
    "RiskGuardConfig",
    "RiskGuardGuidance",
    "RiskGuardResult",
    # V2 Framework - Intents
    "Intent",
    "IntentType",
    "SwapIntent",
    "LPOpenIntent",
    "LPCloseIntent",
    "CollectFeesIntent",
    "BorrowIntent",
    "RepayIntent",
    "HoldIntent",
    "IntentCompiler",
    "IntentCompilerConfig",
    "CompilationResult",
    "CompilationStatus",
    "TransactionData",
    "TokenInfo",
    "PriceInfo",
    "DefaultSwapAdapter",
    "DEFAULT_GAS_ESTIMATES",
    "PROTOCOL_ROUTERS",
    # V2 Framework - State management
    "StateManager",
    "StateTier",
    "StateData",
    "StateConflictError",
    "StateNotFoundError",
    "TierMetrics",
    "StateManagerConfig",
    "PostgresConfig",
    # V2 Framework - State migrations
    "StateMigration",
    "MigrationResult",
    "MigrationRegistry",
    "MigrationError",
    "MigrationNotFoundError",
    "RollbackNotSafeError",
    "RollbackInfo",
    "get_registry",
    "register_migration",
    "migration",
    "migrate",
    "auto_migrate",
    "migrate_state_data",
    "needs_migration",
    "check_rollback_safety",
    "get_rollback_safe_version",
    # V2 Framework - Backtesting
    "BacktestMetrics",
    "BacktestResult",
    "TradeRecord",
    # V2 Framework - Alerting
    "AlertManager",
    "AlertSendResult",
    "CooldownTracker",
    "EscalationLevel",
    "EscalationPolicy",
    "EscalationResult",
    "EscalationState",
    "EscalationStatus",
    # V2 Framework - Services
    "AllowanceInfo",
    "BalanceInfo",
    "BorrowPosition",
    "EmergencyManager",
    "EmergencyResult",
    "FullPositionSummary",
    "GetPositionCallback",
    "LPPositionInfo",
    "OperatorCardGenerator",
    "PauseStrategyCallback",
    "PendingTransaction",
    "StrategySnapshot",
    "StuckDetectionResult",
    "StuckDetector",
    "TokenPosition",
    "create_emergency_manager",
    # V2 Framework - API
    "timeline_router",
    "TimelineEvent",
    "TimelineEventType",
    "TimelineResponse",
    # V2 Framework - Deployment
    "CanaryDeployment",
    "CanaryConfig",
    "CanaryState",
    "CanaryStatus",
    "CanaryMetrics",
    "CanaryDecision",
    "CanaryResult",
    "DeployCanaryResult",
    "CanaryEventType",
    "CanaryComparison",
    "PromotionCriteria",
    # V2 Framework - A/B Testing
    "ABTest",
    "ABTestConfig",
    "ABTestManager",
    "ABTestStatus",
    "ABTestResult",
    "VariantMetrics",
    "VariantComparison",
    "StatisticalResult",
    "ABTestEventType",
    "CreateTestResult",
    "EndTestResult",
    # V2 Framework - Logging
    "configure_logging",
    "get_logger",
    "add_context",
    "clear_context",
    "LogLevel",
    "LogFormat",
    # V2 Framework - CLI helpers
    "new_strategy",
    # V2 Framework - Quant Data Layer
    "DataEnvelope",
    "DataMeta",
    "DataClassification",
    "Instrument",
    "resolve_instrument",
    "DataUnavailableError",
    "LowConfidenceError",
    "PoolPrice",
    "AggregatedPrice",
    "PoolAnalytics",
    "PoolSnapshot",
    "LiquidityDepth",
    "SlippageEstimate",
    "VolatilityResult",
    "PortfolioRisk",
    "RiskConventions",
    "VaRMethod",
    "VaultDepositIntent",
    "VaultRedeemIntent",
    "YieldOpportunity",
    "DataRouter",
    "CircuitBreaker",
    "DataProvider",
]

# --- Lazy resolution dispatch ---------------------------------------------------

_CORE_ENUM_NAMES: frozenset[str] = frozenset(
    {
        "ActionType",
        "Chain",
        "CoSigners",
        "ExecutionStatus",
        "Network",
        "SwapSide",
        "TransactionType",
    }
)

# Every other public name is re-exported from the top-level framework package,
# whose own __getattr__ resolves to the right subpackage.
_FRAMEWORK_NAMES: frozenset[str] = frozenset(__all__) - {
    "__version__",
    "Strategy",
    *_CORE_ENUM_NAMES,
}


def __getattr__(name: str) -> object:
    import importlib

    if name == "Strategy":
        attr = importlib.import_module("almanak.framework").IntentStrategy
    elif name in _CORE_ENUM_NAMES:
        attr = getattr(importlib.import_module("almanak.core.enums"), name)
    elif name in _FRAMEWORK_NAMES:
        attr = getattr(importlib.import_module("almanak.framework"), name)
    else:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    globals()[name] = attr
    return attr


def __dir__() -> list[str]:
    return sorted(set(__all__) | set(globals()))
