from ._version import __version__

# Framework re-exports (common types)
from .core.enums import (
    ActionType,
    Chain,
    CoSigners,
    ExecutionStatus,
    Network,
    Protocol,
    SwapSide,
    TransactionType,
)
from .core.models.action import Action
from .core.models.action_bundle import ActionBundle

# V2 Framework exports
from .framework import (
    DEFAULT_GAS_ESTIMATES,
    PROTOCOL_ROUTERS,
    # Strategy registry
    STRATEGY_REGISTRY,
    # A/B Testing
    ABTest,
    ABTestConfig,
    ABTestEventType,
    ABTestManager,
    ABTestResult,
    ABTestStatus,
    # Quant Data Layer - key public types
    AggregatedPrice,
    # Alerting
    AlertManager,
    AlertSendResult,
    # Services
    AllowanceInfo,
    # Backtesting
    BacktestMetrics,
    BacktestResult,
    BalanceInfo,
    BalanceProvider,
    BorrowIntent,
    BorrowPosition,
    CanaryComparison,
    CanaryConfig,
    CanaryDecision,
    # Deployment
    CanaryDeployment,
    CanaryEventType,
    CanaryMetrics,
    CanaryResult,
    CanaryState,
    CanaryStatus,
    CircuitBreaker,
    CompilationResult,
    CompilationStatus,
    # Config
    ConfigSnapshot,
    CooldownTracker,
    CreateTestResult,
    DataClassification,
    DataEnvelope,
    DataMeta,
    DataProvider,
    DataRouter,
    DataUnavailableError,
    DefaultSwapAdapter,
    DeployCanaryResult,
    EmergencyManager,
    EmergencyResult,
    EndTestResult,
    EscalationLevel,
    EscalationPolicy,
    EscalationResult,
    EscalationState,
    EscalationStatus,
    ExecutionResult,
    FullPositionSummary,
    GetPositionCallback,
    HoldIntent,
    Instrument,
    # Intents
    Intent,
    IntentCompiler,
    IntentCompilerConfig,
    # Strategy base classes
    IntentStrategy,
    IntentType,
    LiquidityDepth,
    LogFormat,
    LogLevel,
    LowConfidenceError,
    LPCloseIntent,
    LPOpenIntent,
    LPPositionInfo,
    MarketSnapshot,
    MigrationError,
    MigrationNotFoundError,
    MigrationRegistry,
    MigrationResult,
    NotificationCallback,
    OperatorCardGenerator,
    PauseStrategyCallback,
    PendingTransaction,
    PoolAnalytics,
    PoolPrice,
    PoolSnapshot,
    PortfolioRisk,
    PostgresConfig,
    PriceData,
    PriceInfo,
    PriceOracle,
    PromotionCriteria,
    RepayIntent,
    RiskConventions,
    RiskGuard,
    RiskGuardConfig,
    RiskGuardGuidance,
    RiskGuardResult,
    RollbackInfo,
    RollbackNotSafeError,
    RSIData,
    RSIProvider,
    SlippageEstimate,
    StateConflictError,
    StateData,
    # State management
    StateManager,
    StateManagerConfig,
    # State migrations
    StateMigration,
    StateNotFoundError,
    StateTier,
    StatisticalResult,
    StrategyBase,
    StrategyMetadata,
    StrategySnapshot,
    StuckDetectionResult,
    StuckDetector,
    SwapIntent,
    TierMetrics,
    TimelineEvent,
    TimelineEventType,
    TimelineResponse,
    TokenBalance,
    TokenInfo,
    TokenPosition,
    TradeRecord,
    TransactionData,
    VariantComparison,
    VariantMetrics,
    VaRMethod,
    VaultDepositIntent,
    VaultRedeemIntent,
    VolatilityResult,
    YieldOpportunity,
    add_context,
    almanak_strategy,
    auto_migrate,
    check_rollback_safety,
    clear_context,
    # Logging
    configure_logging,
    create_emergency_manager,
    get_logger,
    get_registry,
    get_rollback_safe_version,
    get_strategy,
    list_strategies,
    migrate,
    migrate_state_data,
    migration,
    needs_migration,
    # CLI helpers
    new_strategy,
    register_migration,
    register_strategy,
    resolve_instrument,
    # API
    timeline_router,
    unregister_strategy,
)

# Backward compatibility alias - Strategy maps to IntentStrategy
Strategy = IntentStrategy

__all__ = [
    "__version__",
    # Framework - Enums
    "ActionType",
    "Chain",
    "CoSigners",
    "ExecutionStatus",
    "Network",
    "Protocol",
    "SwapSide",
    "TransactionType",
    # Framework - Models
    "Action",
    "ActionBundle",
    # V2 Framework - Strategy base classes
    "Strategy",  # Alias for IntentStrategy
    "IntentStrategy",
    "StrategyBase",
    "MarketSnapshot",
    "TokenBalance",
    "PriceData",
    "RSIData",
    "PriceOracle",
    "RSIProvider",
    "BalanceProvider",
    "ExecutionResult",
    "almanak_strategy",
    "StrategyMetadata",
    # V2 Framework - Strategy registry
    "STRATEGY_REGISTRY",
    "get_strategy",
    "list_strategies",
    "register_strategy",
    "unregister_strategy",
    # V2 Framework - Config
    "ConfigSnapshot",
    "NotificationCallback",
    "RiskGuard",
    "RiskGuardConfig",
    "RiskGuardGuidance",
    "RiskGuardResult",
    # V2 Framework - Intents
    "Intent",
    "IntentType",
    "SwapIntent",
    "LPOpenIntent",
    "LPCloseIntent",
    "BorrowIntent",
    "RepayIntent",
    "HoldIntent",
    "IntentCompiler",
    "IntentCompilerConfig",
    "CompilationResult",
    "CompilationStatus",
    "TransactionData",
    "TokenInfo",
    "PriceInfo",
    "DefaultSwapAdapter",
    "DEFAULT_GAS_ESTIMATES",
    "PROTOCOL_ROUTERS",
    # V2 Framework - State management
    "StateManager",
    "StateTier",
    "StateData",
    "StateConflictError",
    "StateNotFoundError",
    "TierMetrics",
    "StateManagerConfig",
    "PostgresConfig",
    # V2 Framework - State migrations
    "StateMigration",
    "MigrationResult",
    "MigrationRegistry",
    "MigrationError",
    "MigrationNotFoundError",
    "RollbackNotSafeError",
    "RollbackInfo",
    "get_registry",
    "register_migration",
    "migration",
    "migrate",
    "auto_migrate",
    "migrate_state_data",
    "needs_migration",
    "check_rollback_safety",
    "get_rollback_safe_version",
    # V2 Framework - Backtesting
    "BacktestMetrics",
    "BacktestResult",
    "TradeRecord",
    # V2 Framework - Alerting
    "AlertManager",
    "AlertSendResult",
    "CooldownTracker",
    "EscalationLevel",
    "EscalationPolicy",
    "EscalationResult",
    "EscalationState",
    "EscalationStatus",
    # V2 Framework - Services
    "AllowanceInfo",
    "BalanceInfo",
    "BorrowPosition",
    "EmergencyManager",
    "EmergencyResult",
    "FullPositionSummary",
    "GetPositionCallback",
    "LPPositionInfo",
    "OperatorCardGenerator",
    "PauseStrategyCallback",
    "PendingTransaction",
    "StrategySnapshot",
    "StuckDetectionResult",
    "StuckDetector",
    "TokenPosition",
    "create_emergency_manager",
    # V2 Framework - API
    "timeline_router",
    "TimelineEvent",
    "TimelineEventType",
    "TimelineResponse",
    # V2 Framework - Deployment
    "CanaryDeployment",
    "CanaryConfig",
    "CanaryState",
    "CanaryStatus",
    "CanaryMetrics",
    "CanaryDecision",
    "CanaryResult",
    "DeployCanaryResult",
    "CanaryEventType",
    "CanaryComparison",
    "PromotionCriteria",
    # V2 Framework - A/B Testing
    "ABTest",
    "ABTestConfig",
    "ABTestManager",
    "ABTestStatus",
    "ABTestResult",
    "VariantMetrics",
    "VariantComparison",
    "StatisticalResult",
    "ABTestEventType",
    "CreateTestResult",
    "EndTestResult",
    # V2 Framework - Logging
    "configure_logging",
    "get_logger",
    "add_context",
    "clear_context",
    "LogLevel",
    "LogFormat",
    # V2 Framework - CLI helpers
    "new_strategy",
    # V2 Framework - Quant Data Layer
    "DataEnvelope",
    "DataMeta",
    "DataClassification",
    "Instrument",
    "resolve_instrument",
    "DataUnavailableError",
    "LowConfidenceError",
    "PoolPrice",
    "AggregatedPrice",
    "PoolAnalytics",
    "PoolSnapshot",
    "LiquidityDepth",
    "SlippageEstimate",
    "VolatilityResult",
    "PortfolioRisk",
    "RiskConventions",
    "VaRMethod",
    "VaultDepositIntent",
    "VaultRedeemIntent",
    "YieldOpportunity",
    "DataRouter",
    "CircuitBreaker",
    "DataProvider",
]
