"""Persistent cache for compiled intent bundles.

The `ax` CLI is a one-shot process, so the previous in-process dict was
empty on every invocation and broke the ``compile_intent`` ->
``execute_compiled_bundle`` handoff across shell commands. This module
persists bundles to ``${XDG_CACHE_HOME:-~/.cache}/almanak/bundles/`` with a
15-minute TTL, while keeping an in-memory LRU as the hot layer for
same-process callers (agent loops, MCP server).

Entries are keyed by UUID4 ``bundle_id`` (generated by the executor).
Files use 0600 permissions; the cache directory uses 0700.

See VIB-2996.
"""

from __future__ import annotations

import base64
import binascii
import json
import logging
import os
import tempfile
import time
from collections import OrderedDict
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)

DEFAULT_TTL_SECONDS = 15 * 60
DEFAULT_MAX_MEMORY_ENTRIES = 100

# Schema version:
#   1 -> initial layout (chain, bundle_b64, args, created_at, ttl_seconds)
#   2 -> adds wallet_address and strategy_id so the executor can reject a
#        cached bundle compiled under a different identity when the cache is
#        shared across CLI invocations. v1 files are treated as corrupt
#        (and unlinked) because the older `args` dict is not trusted to
#        contain the originating wallet.
_SCHEMA_VERSION = 2


class BundleCacheError(Exception):
    """Base class for bundle-cache lookup failures."""


class BundleExpiredError(BundleCacheError):
    """Raised when a bundle exists on disk but has exceeded its TTL.

    The stale file is removed before this error is raised.
    """

    def __init__(self, bundle_id: str, age_seconds: float, ttl_seconds: int) -> None:
        self.bundle_id = bundle_id
        self.age_seconds = age_seconds
        self.ttl_seconds = ttl_seconds
        over_by = max(0.0, age_seconds - ttl_seconds)
        super().__init__(
            f"Bundle '{bundle_id}' expired {over_by:.0f}s ago "
            f"(age {age_seconds:.0f}s > ttl {ttl_seconds}s). "
            "Recompile with compile_intent."
        )


@dataclass
class BundleCacheEntry:
    chain: str
    bundle_bytes: bytes
    args: dict
    created_at: float
    ttl_seconds: int
    wallet_address: str = ""
    strategy_id: str = ""

    def is_expired(self, now: float | None = None) -> bool:
        return ((now if now is not None else time.time()) - self.created_at) > self.ttl_seconds

    def age_seconds(self, now: float | None = None) -> float:
        return (now if now is not None else time.time()) - self.created_at


def default_cache_dir() -> Path:
    """Return the default cache directory, honouring ``XDG_CACHE_HOME``."""
    base = os.environ.get("XDG_CACHE_HOME") or str(Path.home() / ".cache")
    return Path(base) / "almanak" / "bundles"


class BundleCache:
    """Two-layer cache: in-memory LRU + persistent JSON files on disk.

    Semantics:
      * ``get()`` returns the entry on hit, ``None`` on miss.
      * ``get()`` raises :class:`BundleExpiredError` when a bundle exists
        on disk but has aged past its TTL (and removes the stale file).
      * ``put()`` writes to both layers. Disk write failures are logged
        but do not raise — the in-memory copy still works for the
        current process.
      * ``pop()`` removes from both layers; missing entries are a no-op.
    """

    def __init__(
        self,
        cache_dir: Path | None = None,
        *,
        max_memory_entries: int = DEFAULT_MAX_MEMORY_ENTRIES,
        default_ttl_seconds: int = DEFAULT_TTL_SECONDS,
    ) -> None:
        self._cache_dir = Path(cache_dir) if cache_dir is not None else default_cache_dir()
        self._max_memory = max_memory_entries
        self._default_ttl = default_ttl_seconds
        self._memory: OrderedDict[str, BundleCacheEntry] = OrderedDict()

    @property
    def cache_dir(self) -> Path:
        return self._cache_dir

    @property
    def default_ttl_seconds(self) -> int:
        return self._default_ttl

    def get(self, bundle_id: str) -> BundleCacheEntry | None:
        entry = self._memory.get(bundle_id)
        if entry is not None:
            self._memory.move_to_end(bundle_id)
            if entry.is_expired():
                age = entry.age_seconds()
                ttl = entry.ttl_seconds
                self._memory.pop(bundle_id, None)
                self._remove_disk(bundle_id)
                raise BundleExpiredError(bundle_id, age, ttl)
            return entry

        try:
            path = self._path_for(bundle_id)
        except ValueError:
            # Malformed bundle_id (e.g. empty after sanitisation): treat as a
            # plain miss so the caller surfaces a clean validation error
            # instead of an internal_error. Typos and bad LLM output hit this.
            return None
        if not path.is_file():
            return None
        try:
            entry = self._read_from_disk(path)
        except (OSError, json.JSONDecodeError, KeyError, ValueError) as exc:
            logger.warning(
                "bundle_cache.disk_read_failed bundle_id=%s error=%s",
                bundle_id,
                exc,
            )
            try:
                path.unlink()
            except OSError:
                pass
            return None

        if entry.is_expired():
            age = entry.age_seconds()
            ttl = entry.ttl_seconds
            self._remove_disk(bundle_id)
            raise BundleExpiredError(bundle_id, age, ttl)

        self._insert_memory(bundle_id, entry)
        return entry

    def put(
        self,
        bundle_id: str,
        chain: str,
        bundle_bytes: bytes,
        args: dict,
        *,
        wallet_address: str = "",
        strategy_id: str = "",
        ttl_seconds: int | None = None,
    ) -> None:
        entry = BundleCacheEntry(
            chain=chain,
            bundle_bytes=bundle_bytes,
            args=args,
            created_at=time.time(),
            ttl_seconds=ttl_seconds if ttl_seconds is not None else self._default_ttl,
            wallet_address=wallet_address,
            strategy_id=strategy_id,
        )
        self._insert_memory(bundle_id, entry)
        try:
            self._write_to_disk(bundle_id, entry)
        except OSError as exc:
            logger.warning(
                "bundle_cache.disk_write_failed bundle_id=%s error=%s",
                bundle_id,
                exc,
            )

    def pop(self, bundle_id: str) -> None:
        self._memory.pop(bundle_id, None)
        self._remove_disk(bundle_id)

    def list_entries(self) -> list[tuple[str, BundleCacheEntry]]:
        """Return all disk-persisted entries (newest first).

        Stale/corrupt files are skipped silently; expired files are
        retained so ``ax bundle-list`` can show their age. Callers that
        want to prune expired entries should call ``prune_expired()``.
        """
        if not self._cache_dir.is_dir():
            return []
        entries: list[tuple[str, BundleCacheEntry]] = []
        for path in self._cache_dir.glob("*.json"):
            if path.name.startswith("."):
                continue
            bundle_id = path.stem
            try:
                entry = self._read_from_disk(path)
            except (OSError, json.JSONDecodeError, KeyError, ValueError):
                continue
            entries.append((bundle_id, entry))
        entries.sort(key=lambda kv: kv[1].created_at, reverse=True)
        return entries

    def prune_expired(self) -> int:
        removed = 0
        for bundle_id, entry in list(self._memory.items()):
            if entry.is_expired():
                self._memory.pop(bundle_id, None)
                self._remove_disk(bundle_id)
                removed += 1
        if self._cache_dir.is_dir():
            for path in self._cache_dir.glob("*.json"):
                if path.name.startswith("."):
                    continue
                try:
                    entry = self._read_from_disk(path)
                except (OSError, json.JSONDecodeError, KeyError, ValueError):
                    try:
                        path.unlink()
                        removed += 1
                    except OSError:
                        pass
                    continue
                if entry.is_expired():
                    try:
                        path.unlink()
                        removed += 1
                    except OSError:
                        pass
        return removed

    def clear(self) -> int:
        # Count disk unlinks only. Entries can exist in both memory and on
        # disk, so summing both layers would double-count them.
        self._memory.clear()
        count = 0
        if self._cache_dir.is_dir():
            for path in self._cache_dir.glob("*.json"):
                if path.name.startswith("."):
                    continue
                try:
                    path.unlink()
                    count += 1
                except OSError:
                    pass
        return count

    def _insert_memory(self, bundle_id: str, entry: BundleCacheEntry) -> None:
        # A disk-only cache (max_memory_entries=0) is a legitimate caller
        # choice — e.g., when an embedding process wants hard per-entry fsync
        # semantics. Skip the memory layer entirely rather than crashing on
        # `popitem()` against an empty OrderedDict. (CodeRabbit round 2.)
        if self._max_memory <= 0:
            return
        if bundle_id in self._memory:
            self._memory[bundle_id] = entry
            self._memory.move_to_end(bundle_id)
            return
        if len(self._memory) >= self._max_memory:
            self._memory.popitem(last=False)
        self._memory[bundle_id] = entry

    def _path_for(self, bundle_id: str) -> Path:
        # Defensive sanitisation: bundle_id is a UUID4 from the executor,
        # but the disk cache is user-writable so never join arbitrary input.
        safe = "".join(c for c in bundle_id if c.isalnum() or c in "-_")
        if not safe:
            raise ValueError(f"invalid bundle_id: {bundle_id!r}")
        return self._cache_dir / f"{safe}.json"

    def _ensure_dir(self) -> None:
        self._cache_dir.mkdir(parents=True, exist_ok=True)
        try:
            os.chmod(self._cache_dir, 0o700)
        except OSError:
            pass

    def _write_to_disk(self, bundle_id: str, entry: BundleCacheEntry) -> None:
        self._ensure_dir()
        path = self._path_for(bundle_id)
        payload = {
            "schema_version": _SCHEMA_VERSION,
            "chain": entry.chain,
            "bundle_b64": base64.b64encode(entry.bundle_bytes).decode("ascii"),
            "args": entry.args,
            "created_at": entry.created_at,
            "ttl_seconds": entry.ttl_seconds,
            "wallet_address": entry.wallet_address,
            "strategy_id": entry.strategy_id,
        }
        fd, tmp = tempfile.mkstemp(prefix=".bundle-", suffix=".json", dir=str(self._cache_dir))
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as fh:
                json.dump(payload, fh, default=str)
            os.chmod(tmp, 0o600)
            os.replace(tmp, path)
        except Exception:
            try:
                os.unlink(tmp)
            except OSError:
                pass
            raise

    def _read_from_disk(self, path: Path) -> BundleCacheEntry:
        with path.open("r", encoding="utf-8") as fh:
            payload = json.load(fh)
        if payload.get("schema_version") != _SCHEMA_VERSION:
            raise ValueError(f"unsupported schema_version: {payload.get('schema_version')!r}")

        # Strict type validation: a corrupt or malicious payload that slips
        # through JSON parsing (e.g. {"chain": []}) must be treated as a
        # corrupt file and unlinked, NOT returned and then blown up later
        # inside execute_compiled_bundle on ``.lower()`` or policy checks.
        # (CodeRabbit round 2 + Claude auditor item #5.)
        chain = payload.get("chain")
        bundle_b64 = payload.get("bundle_b64")
        raw_args = payload.get("args", {})
        created_at = payload.get("created_at")
        ttl_seconds = payload.get("ttl_seconds")
        wallet_address = payload.get("wallet_address", "")
        strategy_id = payload.get("strategy_id", "")

        if not isinstance(chain, str) or not chain:
            raise ValueError(f"invalid chain: {chain!r}")
        if not isinstance(bundle_b64, str):
            raise ValueError("bundle_b64 must be a string")
        if not isinstance(raw_args, dict):
            raise ValueError(f"bundle args must be a dict, got {type(raw_args).__name__}")
        if not isinstance(created_at, int | float):
            raise ValueError(f"invalid created_at: {created_at!r}")
        if not isinstance(ttl_seconds, int) or ttl_seconds <= 0:
            raise ValueError(f"invalid ttl_seconds: {ttl_seconds!r}")
        if not isinstance(wallet_address, str) or not isinstance(strategy_id, str):
            raise ValueError("wallet_address and strategy_id must be strings")

        try:
            bundle_bytes = base64.b64decode(bundle_b64, validate=True)
        except (ValueError, binascii.Error) as exc:
            raise ValueError(f"bundle_b64 is not valid base64: {exc}") from exc

        return BundleCacheEntry(
            chain=chain,
            bundle_bytes=bundle_bytes,
            args=raw_args,
            created_at=float(created_at),
            ttl_seconds=ttl_seconds,
            wallet_address=wallet_address,
            strategy_id=strategy_id,
        )

    def _remove_disk(self, bundle_id: str) -> None:
        try:
            path = self._path_for(bundle_id)
        except ValueError:
            return
        try:
            path.unlink()
        except FileNotFoundError:
            pass
        except OSError as exc:
            logger.warning(
                "bundle_cache.disk_unlink_failed bundle_id=%s error=%s",
                bundle_id,
                exc,
            )
