"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Aster Pro (off-chain order book) proxy. The gateway holds the main-wallet
key and the approved agent key, signs every request, and talks to
fapi.asterdex.com; the strategy container only sends these RPCs.
``package`` matches the gateway proto so method paths share its namespace.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AsterGetMarketRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    """e.g. "ETHUSDT" """
    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["symbol", b"symbol"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AsterGetMarketRequest: _TypeAlias = AsterGetMarketRequest  # noqa: Y015

@_typing.final
class AsterMarketResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    SYMBOL_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    MARK_PRICE_FIELD_NUMBER: _builtins.int
    STEP_SIZE_FIELD_NUMBER: _builtins.int
    MIN_QTY_FIELD_NUMBER: _builtins.int
    MIN_NOTIONAL_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    symbol: _builtins.str
    status: _builtins.str
    mark_price: _builtins.str
    """Decimal string"""
    step_size: _builtins.str
    min_qty: _builtins.str
    min_notional: _builtins.str
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
        symbol: _builtins.str = ...,
        status: _builtins.str = ...,
        mark_price: _builtins.str = ...,
        step_size: _builtins.str = ...,
        min_qty: _builtins.str = ...,
        min_notional: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "mark_price", b"mark_price", "min_notional", b"min_notional", "min_qty", b"min_qty", "status", b"status", "step_size", b"step_size", "success", b"success", "symbol", b"symbol"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AsterMarketResponse: _TypeAlias = AsterMarketResponse  # noqa: Y015

@_typing.final
class AsterPlaceMarketOrderRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    IS_LONG_FIELD_NUMBER: _builtins.int
    NOTIONAL_USD_FIELD_NUMBER: _builtins.int
    CLOSE_POSITION_FIELD_NUMBER: _builtins.int
    LEVERAGE_FIELD_NUMBER: _builtins.int
    CLIENT_ORDER_ID_FIELD_NUMBER: _builtins.int
    WALLET_ADDRESS_FIELD_NUMBER: _builtins.int
    MAX_SLIPPAGE_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    is_long: _builtins.bool
    """direction of the POSITION being opened or closed"""
    notional_usd: _builtins.str
    """open: target notional, rounded DOWN to the step size"""
    close_position: _builtins.bool
    """close: flatten the whole one-way position (reduceOnly)"""
    leverage: _builtins.int
    """open: set before ordering; 0 leaves the account setting"""
    client_order_id: _builtins.str
    """idempotency key; reconcile by it on unknown outcome"""
    wallet_address: _builtins.str
    """must equal the gateway's configured main wallet"""
    max_slippage: _builtins.str
    """fraction (0.01 = 1%): the order is a LIMIT IOC bounded at mark x (1 +/- max_slippage)"""
    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
        is_long: _builtins.bool = ...,
        notional_usd: _builtins.str = ...,
        close_position: _builtins.bool = ...,
        leverage: _builtins.int = ...,
        client_order_id: _builtins.str = ...,
        wallet_address: _builtins.str = ...,
        max_slippage: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_order_id", b"client_order_id", "close_position", b"close_position", "is_long", b"is_long", "leverage", b"leverage", "max_slippage", b"max_slippage", "notional_usd", b"notional_usd", "symbol", b"symbol", "wallet_address", b"wallet_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AsterPlaceMarketOrderRequest: _TypeAlias = AsterPlaceMarketOrderRequest  # noqa: Y015

@_typing.final
class AsterOrderResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    OUTCOME_UNKNOWN_FIELD_NUMBER: _builtins.int
    ORDER_ID_FIELD_NUMBER: _builtins.int
    CLIENT_ORDER_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    SIDE_FIELD_NUMBER: _builtins.int
    EXECUTED_QTY_FIELD_NUMBER: _builtins.int
    AVG_PRICE_FIELD_NUMBER: _builtins.int
    CUM_QUOTE_FIELD_NUMBER: _builtins.int
    REQUESTED_QTY_FIELD_NUMBER: _builtins.int
    FEE_FIELD_NUMBER: _builtins.int
    FEE_ASSET_FIELD_NUMBER: _builtins.int
    REALIZED_PNL_FIELD_NUMBER: _builtins.int
    ORDER_NOT_FOUND_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    outcome_unknown: _builtins.bool
    """transport/5xx: order may exist, reconcile by client_order_id"""
    order_id: _builtins.int
    client_order_id: _builtins.str
    status: _builtins.str
    """Aster order status: NEW / FILLED / PARTIALLY_FILLED / ..."""
    side: _builtins.str
    executed_qty: _builtins.str
    avg_price: _builtins.str
    cum_quote: _builtins.str
    """executed notional in quote asset (USDT)"""
    requested_qty: _builtins.str
    fee: _builtins.str
    """summed commission over the order's fills; "" when unread"""
    fee_asset: _builtins.str
    realized_pnl: _builtins.str
    """summed over the order's fills; "" when unread"""
    order_not_found: _builtins.bool
    """GetOrder: the venue has no order under this client id (it never filled)"""
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
        outcome_unknown: _builtins.bool = ...,
        order_id: _builtins.int = ...,
        client_order_id: _builtins.str = ...,
        status: _builtins.str = ...,
        side: _builtins.str = ...,
        executed_qty: _builtins.str = ...,
        avg_price: _builtins.str = ...,
        cum_quote: _builtins.str = ...,
        requested_qty: _builtins.str = ...,
        fee: _builtins.str = ...,
        fee_asset: _builtins.str = ...,
        realized_pnl: _builtins.str = ...,
        order_not_found: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["avg_price", b"avg_price", "client_order_id", b"client_order_id", "cum_quote", b"cum_quote", "error", b"error", "executed_qty", b"executed_qty", "fee", b"fee", "fee_asset", b"fee_asset", "order_id", b"order_id", "order_not_found", b"order_not_found", "outcome_unknown", b"outcome_unknown", "realized_pnl", b"realized_pnl", "requested_qty", b"requested_qty", "side", b"side", "status", b"status", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AsterOrderResponse: _TypeAlias = AsterOrderResponse  # noqa: Y015

@_typing.final
class AsterGetOrderRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    CLIENT_ORDER_ID_FIELD_NUMBER: _builtins.int
    WALLET_ADDRESS_FIELD_NUMBER: _builtins.int
    CLOSE_POSITION_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    client_order_id: _builtins.str
    wallet_address: _builtins.str
    close_position: _builtins.bool
    """the order closed a position: only a complete fill is success"""
    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
        client_order_id: _builtins.str = ...,
        wallet_address: _builtins.str = ...,
        close_position: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_order_id", b"client_order_id", "close_position", b"close_position", "symbol", b"symbol", "wallet_address", b"wallet_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AsterGetOrderRequest: _TypeAlias = AsterGetOrderRequest  # noqa: Y015

@_typing.final
class AsterGetPositionsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    WALLET_ADDRESS_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    """empty = all symbols"""
    wallet_address: _builtins.str
    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
        wallet_address: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["symbol", b"symbol", "wallet_address", b"wallet_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AsterGetPositionsRequest: _TypeAlias = AsterGetPositionsRequest  # noqa: Y015

@_typing.final
class AsterPosition(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    POSITION_AMT_FIELD_NUMBER: _builtins.int
    ENTRY_PRICE_FIELD_NUMBER: _builtins.int
    MARK_PRICE_FIELD_NUMBER: _builtins.int
    UNREALIZED_PNL_FIELD_NUMBER: _builtins.int
    LEVERAGE_FIELD_NUMBER: _builtins.int
    NOTIONAL_FIELD_NUMBER: _builtins.int
    LIQUIDATION_PRICE_FIELD_NUMBER: _builtins.int
    POSITION_SIDE_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    position_amt: _builtins.str
    """signed: >0 long, <0 short"""
    entry_price: _builtins.str
    mark_price: _builtins.str
    unrealized_pnl: _builtins.str
    leverage: _builtins.str
    notional: _builtins.str
    liquidation_price: _builtins.str
    position_side: _builtins.str
    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
        position_amt: _builtins.str = ...,
        entry_price: _builtins.str = ...,
        mark_price: _builtins.str = ...,
        unrealized_pnl: _builtins.str = ...,
        leverage: _builtins.str = ...,
        notional: _builtins.str = ...,
        liquidation_price: _builtins.str = ...,
        position_side: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry_price", b"entry_price", "leverage", b"leverage", "liquidation_price", b"liquidation_price", "mark_price", b"mark_price", "notional", b"notional", "position_amt", b"position_amt", "position_side", b"position_side", "symbol", b"symbol", "unrealized_pnl", b"unrealized_pnl"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AsterPosition: _TypeAlias = AsterPosition  # noqa: Y015

@_typing.final
class AsterPositionsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    POSITIONS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    @_builtins.property
    def positions(self) -> _containers.RepeatedCompositeFieldContainer[Global___AsterPosition]: ...
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
        positions: _abc.Iterable[Global___AsterPosition] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "positions", b"positions", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AsterPositionsResponse: _TypeAlias = AsterPositionsResponse  # noqa: Y015

@_typing.final
class AsterGetBalancesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WALLET_ADDRESS_FIELD_NUMBER: _builtins.int
    wallet_address: _builtins.str
    def __init__(
        self,
        *,
        wallet_address: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["wallet_address", b"wallet_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AsterGetBalancesRequest: _TypeAlias = AsterGetBalancesRequest  # noqa: Y015

@_typing.final
class AsterBalance(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ASSET_FIELD_NUMBER: _builtins.int
    BALANCE_FIELD_NUMBER: _builtins.int
    AVAILABLE_BALANCE_FIELD_NUMBER: _builtins.int
    CROSS_UNREALIZED_PNL_FIELD_NUMBER: _builtins.int
    asset: _builtins.str
    balance: _builtins.str
    available_balance: _builtins.str
    cross_unrealized_pnl: _builtins.str
    def __init__(
        self,
        *,
        asset: _builtins.str = ...,
        balance: _builtins.str = ...,
        available_balance: _builtins.str = ...,
        cross_unrealized_pnl: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["asset", b"asset", "available_balance", b"available_balance", "balance", b"balance", "cross_unrealized_pnl", b"cross_unrealized_pnl"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AsterBalance: _TypeAlias = AsterBalance  # noqa: Y015

@_typing.final
class AsterPendingTransfer(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    ASSET_FIELD_NUMBER: _builtins.int
    AMOUNT_FIELD_NUMBER: _builtins.int
    FEE_FIELD_NUMBER: _builtins.int
    TRANSFER_ID_FIELD_NUMBER: _builtins.int
    type: _builtins.str
    """DEPOSIT or WITHDRAW"""
    asset: _builtins.str
    amount: _builtins.str
    """gross amount as recorded by the venue"""
    fee: _builtins.str
    """withdrawals: current venue fee for the chain; "" when unknown"""
    transfer_id: _builtins.str
    def __init__(
        self,
        *,
        type: _builtins.str = ...,
        asset: _builtins.str = ...,
        amount: _builtins.str = ...,
        fee: _builtins.str = ...,
        transfer_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount", "asset", b"asset", "fee", b"fee", "transfer_id", b"transfer_id", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AsterPendingTransfer: _TypeAlias = AsterPendingTransfer  # noqa: Y015

@_typing.final
class AsterBalancesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    BALANCES_FIELD_NUMBER: _builtins.int
    PENDING_TRANSFERS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    @_builtins.property
    def balances(self) -> _containers.RepeatedCompositeFieldContainer[Global___AsterBalance]: ...
    @_builtins.property
    def pending_transfers(self) -> _containers.RepeatedCompositeFieldContainer[Global___AsterPendingTransfer]:
        """Deposits not yet credited and withdrawals not yet paid out (venue state PROCESSING)."""

    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
        balances: _abc.Iterable[Global___AsterBalance] | None = ...,
        pending_transfers: _abc.Iterable[Global___AsterPendingTransfer] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["balances", b"balances", "error", b"error", "pending_transfers", b"pending_transfers", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AsterBalancesResponse: _TypeAlias = AsterBalancesResponse  # noqa: Y015

@_typing.final
class AsterWithdrawRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ASSET_FIELD_NUMBER: _builtins.int
    AMOUNT_FIELD_NUMBER: _builtins.int
    WALLET_ADDRESS_FIELD_NUMBER: _builtins.int
    CLIENT_REQUEST_ID_FIELD_NUMBER: _builtins.int
    asset: _builtins.str
    """margin asset, e.g. "USDT" """
    amount: _builtins.str
    """gross amount (fee deducted from it), or "all" for the full withdrawable balance"""
    wallet_address: _builtins.str
    """must equal the gateway's main wallet; also the only receiver"""
    client_request_id: _builtins.str
    """the intent's request id: reconciliation matches an accepted withdrawal by it; a re-send is refused unless it failed"""
    def __init__(
        self,
        *,
        asset: _builtins.str = ...,
        amount: _builtins.str = ...,
        wallet_address: _builtins.str = ...,
        client_request_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount", "asset", b"asset", "client_request_id", b"client_request_id", "wallet_address", b"wallet_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AsterWithdrawRequest: _TypeAlias = AsterWithdrawRequest  # noqa: Y015

@_typing.final
class AsterWithdrawResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    OUTCOME_UNKNOWN_FIELD_NUMBER: _builtins.int
    WITHDRAW_ID_FIELD_NUMBER: _builtins.int
    AMOUNT_FIELD_NUMBER: _builtins.int
    FEE_FIELD_NUMBER: _builtins.int
    RECEIVER_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    outcome_unknown: _builtins.bool
    """transport/5xx: the withdrawal may have been accepted"""
    withdraw_id: _builtins.str
    amount: _builtins.str
    fee: _builtins.str
    receiver: _builtins.str
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
        outcome_unknown: _builtins.bool = ...,
        withdraw_id: _builtins.str = ...,
        amount: _builtins.str = ...,
        fee: _builtins.str = ...,
        receiver: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount", "error", b"error", "fee", b"fee", "outcome_unknown", b"outcome_unknown", "receiver", b"receiver", "success", b"success", "withdraw_id", b"withdraw_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AsterWithdrawResponse: _TypeAlias = AsterWithdrawResponse  # noqa: Y015

@_typing.final
class AsterFindWithdrawalRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WALLET_ADDRESS_FIELD_NUMBER: _builtins.int
    SINCE_MS_FIELD_NUMBER: _builtins.int
    CLIENT_REQUEST_ID_FIELD_NUMBER: _builtins.int
    wallet_address: _builtins.str
    since_ms: _builtins.int
    """withdrawals the venue recorded at or after this time (epoch ms)"""
    client_request_id: _builtins.str
    """the attempt's request id; matched exactly when this gateway accepted it"""
    def __init__(
        self,
        *,
        wallet_address: _builtins.str = ...,
        since_ms: _builtins.int = ...,
        client_request_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_request_id", b"client_request_id", "since_ms", b"since_ms", "wallet_address", b"wallet_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AsterFindWithdrawalRequest: _TypeAlias = AsterFindWithdrawalRequest  # noqa: Y015

@_typing.final
class AsterFindWithdrawalResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    FOUND_FIELD_NUMBER: _builtins.int
    NOT_FOUND_FIELD_NUMBER: _builtins.int
    WITHDRAW_ID_FIELD_NUMBER: _builtins.int
    AMOUNT_FIELD_NUMBER: _builtins.int
    FEE_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    found: _builtins.bool
    """exactly one withdrawal recorded since since_ms"""
    not_found: _builtins.bool
    """none recorded, and enough time has passed that none will be"""
    withdraw_id: _builtins.str
    amount: _builtins.str
    """gross amount as recorded by the venue"""
    fee: _builtins.str
    """current venue fee for the chain"""
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
        found: _builtins.bool = ...,
        not_found: _builtins.bool = ...,
        withdraw_id: _builtins.str = ...,
        amount: _builtins.str = ...,
        fee: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount", "error", b"error", "fee", b"fee", "found", b"found", "not_found", b"not_found", "success", b"success", "withdraw_id", b"withdraw_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AsterFindWithdrawalResponse: _TypeAlias = AsterFindWithdrawalResponse  # noqa: Y015
