# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import aster_perps_pb2 as aster__perps__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aster_perps_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AsterPerpsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMarket = channel.unary_unary(
                '/almanak.gateway.proto.AsterPerpsService/GetMarket',
                request_serializer=aster__perps__pb2.AsterGetMarketRequest.SerializeToString,
                response_deserializer=aster__perps__pb2.AsterMarketResponse.FromString,
                _registered_method=True)
        self.PlaceMarketOrder = channel.unary_unary(
                '/almanak.gateway.proto.AsterPerpsService/PlaceMarketOrder',
                request_serializer=aster__perps__pb2.AsterPlaceMarketOrderRequest.SerializeToString,
                response_deserializer=aster__perps__pb2.AsterOrderResponse.FromString,
                _registered_method=True)
        self.GetOrder = channel.unary_unary(
                '/almanak.gateway.proto.AsterPerpsService/GetOrder',
                request_serializer=aster__perps__pb2.AsterGetOrderRequest.SerializeToString,
                response_deserializer=aster__perps__pb2.AsterOrderResponse.FromString,
                _registered_method=True)
        self.GetPositions = channel.unary_unary(
                '/almanak.gateway.proto.AsterPerpsService/GetPositions',
                request_serializer=aster__perps__pb2.AsterGetPositionsRequest.SerializeToString,
                response_deserializer=aster__perps__pb2.AsterPositionsResponse.FromString,
                _registered_method=True)
        self.GetBalances = channel.unary_unary(
                '/almanak.gateway.proto.AsterPerpsService/GetBalances',
                request_serializer=aster__perps__pb2.AsterGetBalancesRequest.SerializeToString,
                response_deserializer=aster__perps__pb2.AsterBalancesResponse.FromString,
                _registered_method=True)
        self.GetWithdrawalPayout = channel.unary_unary(
                '/almanak.gateway.proto.AsterPerpsService/GetWithdrawalPayout',
                request_serializer=aster__perps__pb2.AsterWithdrawalPayoutRequest.SerializeToString,
                response_deserializer=aster__perps__pb2.AsterWithdrawalPayoutResponse.FromString,
                _registered_method=True)
        self.Withdraw = channel.unary_unary(
                '/almanak.gateway.proto.AsterPerpsService/Withdraw',
                request_serializer=aster__perps__pb2.AsterWithdrawRequest.SerializeToString,
                response_deserializer=aster__perps__pb2.AsterWithdrawResponse.FromString,
                _registered_method=True)
        self.FindWithdrawal = channel.unary_unary(
                '/almanak.gateway.proto.AsterPerpsService/FindWithdrawal',
                request_serializer=aster__perps__pb2.AsterFindWithdrawalRequest.SerializeToString,
                response_deserializer=aster__perps__pb2.AsterFindWithdrawalResponse.FromString,
                _registered_method=True)


class AsterPerpsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMarket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceMarketOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalances(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWithdrawalPayout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Withdraw(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindWithdrawal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AsterPerpsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMarket': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMarket,
                    request_deserializer=aster__perps__pb2.AsterGetMarketRequest.FromString,
                    response_serializer=aster__perps__pb2.AsterMarketResponse.SerializeToString,
            ),
            'PlaceMarketOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceMarketOrder,
                    request_deserializer=aster__perps__pb2.AsterPlaceMarketOrderRequest.FromString,
                    response_serializer=aster__perps__pb2.AsterOrderResponse.SerializeToString,
            ),
            'GetOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrder,
                    request_deserializer=aster__perps__pb2.AsterGetOrderRequest.FromString,
                    response_serializer=aster__perps__pb2.AsterOrderResponse.SerializeToString,
            ),
            'GetPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositions,
                    request_deserializer=aster__perps__pb2.AsterGetPositionsRequest.FromString,
                    response_serializer=aster__perps__pb2.AsterPositionsResponse.SerializeToString,
            ),
            'GetBalances': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalances,
                    request_deserializer=aster__perps__pb2.AsterGetBalancesRequest.FromString,
                    response_serializer=aster__perps__pb2.AsterBalancesResponse.SerializeToString,
            ),
            'GetWithdrawalPayout': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWithdrawalPayout,
                    request_deserializer=aster__perps__pb2.AsterWithdrawalPayoutRequest.FromString,
                    response_serializer=aster__perps__pb2.AsterWithdrawalPayoutResponse.SerializeToString,
            ),
            'Withdraw': grpc.unary_unary_rpc_method_handler(
                    servicer.Withdraw,
                    request_deserializer=aster__perps__pb2.AsterWithdrawRequest.FromString,
                    response_serializer=aster__perps__pb2.AsterWithdrawResponse.SerializeToString,
            ),
            'FindWithdrawal': grpc.unary_unary_rpc_method_handler(
                    servicer.FindWithdrawal,
                    request_deserializer=aster__perps__pb2.AsterFindWithdrawalRequest.FromString,
                    response_serializer=aster__perps__pb2.AsterFindWithdrawalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'almanak.gateway.proto.AsterPerpsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('almanak.gateway.proto.AsterPerpsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AsterPerpsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMarket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.AsterPerpsService/GetMarket',
            aster__perps__pb2.AsterGetMarketRequest.SerializeToString,
            aster__perps__pb2.AsterMarketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceMarketOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.AsterPerpsService/PlaceMarketOrder',
            aster__perps__pb2.AsterPlaceMarketOrderRequest.SerializeToString,
            aster__perps__pb2.AsterOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.AsterPerpsService/GetOrder',
            aster__perps__pb2.AsterGetOrderRequest.SerializeToString,
            aster__perps__pb2.AsterOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.AsterPerpsService/GetPositions',
            aster__perps__pb2.AsterGetPositionsRequest.SerializeToString,
            aster__perps__pb2.AsterPositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.AsterPerpsService/GetBalances',
            aster__perps__pb2.AsterGetBalancesRequest.SerializeToString,
            aster__perps__pb2.AsterBalancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWithdrawalPayout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.AsterPerpsService/GetWithdrawalPayout',
            aster__perps__pb2.AsterWithdrawalPayoutRequest.SerializeToString,
            aster__perps__pb2.AsterWithdrawalPayoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Withdraw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.AsterPerpsService/Withdraw',
            aster__perps__pb2.AsterWithdrawRequest.SerializeToString,
            aster__perps__pb2.AsterWithdrawResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindWithdrawal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.AsterPerpsService/FindWithdrawal',
            aster__perps__pb2.AsterFindWithdrawalRequest.SerializeToString,
            aster__perps__pb2.AsterFindWithdrawalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
