# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from almanak.connectors.polymarket.proto import polymarket_pb2 as polymarket__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in polymarket_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PolymarketServiceStub(object):
    """=============================================================================
    PolymarketService - Polymarket CLOB API proxy
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMarket = channel.unary_unary(
                '/almanak.gateway.proto.PolymarketService/GetMarket',
                request_serializer=polymarket__pb2.PolymarketGetMarketRequest.SerializeToString,
                response_deserializer=polymarket__pb2.PolymarketMarketResponse.FromString,
                _registered_method=True)
        self.GetMarkets = channel.unary_unary(
                '/almanak.gateway.proto.PolymarketService/GetMarkets',
                request_serializer=polymarket__pb2.PolymarketGetMarketsRequest.SerializeToString,
                response_deserializer=polymarket__pb2.PolymarketMarketsResponse.FromString,
                _registered_method=True)
        self.GetSimplifiedMarkets = channel.unary_unary(
                '/almanak.gateway.proto.PolymarketService/GetSimplifiedMarkets',
                request_serializer=polymarket__pb2.PolymarketGetSimplifiedMarketsRequest.SerializeToString,
                response_deserializer=polymarket__pb2.PolymarketSimplifiedMarketsResponse.FromString,
                _registered_method=True)
        self.GetOrderBook = channel.unary_unary(
                '/almanak.gateway.proto.PolymarketService/GetOrderBook',
                request_serializer=polymarket__pb2.PolymarketOrderBookRequest.SerializeToString,
                response_deserializer=polymarket__pb2.PolymarketOrderBookResponse.FromString,
                _registered_method=True)
        self.GetMidpoint = channel.unary_unary(
                '/almanak.gateway.proto.PolymarketService/GetMidpoint',
                request_serializer=polymarket__pb2.PolymarketMidpointRequest.SerializeToString,
                response_deserializer=polymarket__pb2.PolymarketMidpointResponse.FromString,
                _registered_method=True)
        self.GetPrice = channel.unary_unary(
                '/almanak.gateway.proto.PolymarketService/GetPrice',
                request_serializer=polymarket__pb2.PolymarketPriceRequest.SerializeToString,
                response_deserializer=polymarket__pb2.PolymarketPriceResponse.FromString,
                _registered_method=True)
        self.GetSpread = channel.unary_unary(
                '/almanak.gateway.proto.PolymarketService/GetSpread',
                request_serializer=polymarket__pb2.PolymarketSpreadRequest.SerializeToString,
                response_deserializer=polymarket__pb2.PolymarketSpreadResponse.FromString,
                _registered_method=True)
        self.GetTickSize = channel.unary_unary(
                '/almanak.gateway.proto.PolymarketService/GetTickSize',
                request_serializer=polymarket__pb2.PolymarketTickSizeRequest.SerializeToString,
                response_deserializer=polymarket__pb2.PolymarketTickSizeResponse.FromString,
                _registered_method=True)
        self.CreateAndPostOrder = channel.unary_unary(
                '/almanak.gateway.proto.PolymarketService/CreateAndPostOrder',
                request_serializer=polymarket__pb2.PolymarketCreateOrderRequest.SerializeToString,
                response_deserializer=polymarket__pb2.PolymarketOrderResponse.FromString,
                _registered_method=True)
        self.CreateAndPostMarketOrder = channel.unary_unary(
                '/almanak.gateway.proto.PolymarketService/CreateAndPostMarketOrder',
                request_serializer=polymarket__pb2.PolymarketMarketOrderRequest.SerializeToString,
                response_deserializer=polymarket__pb2.PolymarketOrderResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/almanak.gateway.proto.PolymarketService/CancelOrder',
                request_serializer=polymarket__pb2.PolymarketCancelOrderRequest.SerializeToString,
                response_deserializer=polymarket__pb2.PolymarketCancelResponse.FromString,
                _registered_method=True)
        self.CancelOrders = channel.unary_unary(
                '/almanak.gateway.proto.PolymarketService/CancelOrders',
                request_serializer=polymarket__pb2.PolymarketCancelOrdersRequest.SerializeToString,
                response_deserializer=polymarket__pb2.PolymarketCancelResponse.FromString,
                _registered_method=True)
        self.CancelAll = channel.unary_unary(
                '/almanak.gateway.proto.PolymarketService/CancelAll',
                request_serializer=polymarket__pb2.PolymarketCancelAllRequest.SerializeToString,
                response_deserializer=polymarket__pb2.PolymarketCancelResponse.FromString,
                _registered_method=True)
        self.GetPositions = channel.unary_unary(
                '/almanak.gateway.proto.PolymarketService/GetPositions',
                request_serializer=polymarket__pb2.PolymarketGetPositionsRequest.SerializeToString,
                response_deserializer=polymarket__pb2.PolymarketPositionsResponse.FromString,
                _registered_method=True)
        self.GetOpenOrders = channel.unary_unary(
                '/almanak.gateway.proto.PolymarketService/GetOpenOrders',
                request_serializer=polymarket__pb2.PolymarketGetOpenOrdersRequest.SerializeToString,
                response_deserializer=polymarket__pb2.PolymarketOpenOrdersResponse.FromString,
                _registered_method=True)
        self.GetTradesHistory = channel.unary_unary(
                '/almanak.gateway.proto.PolymarketService/GetTradesHistory',
                request_serializer=polymarket__pb2.PolymarketGetTradesRequest.SerializeToString,
                response_deserializer=polymarket__pb2.PolymarketTradesResponse.FromString,
                _registered_method=True)
        self.GetOrder = channel.unary_unary(
                '/almanak.gateway.proto.PolymarketService/GetOrder',
                request_serializer=polymarket__pb2.PolymarketGetOrderRequest.SerializeToString,
                response_deserializer=polymarket__pb2.PolymarketOrderInfoResponse.FromString,
                _registered_method=True)
        self.GetPriceHistory = channel.unary_unary(
                '/almanak.gateway.proto.PolymarketService/GetPriceHistory',
                request_serializer=polymarket__pb2.PolymarketGetPriceHistoryRequest.SerializeToString,
                response_deserializer=polymarket__pb2.PolymarketPriceHistoryResponse.FromString,
                _registered_method=True)
        self.GetTradeTape = channel.unary_unary(
                '/almanak.gateway.proto.PolymarketService/GetTradeTape',
                request_serializer=polymarket__pb2.PolymarketGetTradeTapeRequest.SerializeToString,
                response_deserializer=polymarket__pb2.PolymarketTradeTapeResponse.FromString,
                _registered_method=True)
        self.GetBalanceAllowance = channel.unary_unary(
                '/almanak.gateway.proto.PolymarketService/GetBalanceAllowance',
                request_serializer=polymarket__pb2.PolymarketBalanceAllowanceRequest.SerializeToString,
                response_deserializer=polymarket__pb2.PolymarketBalanceAllowanceResponse.FromString,
                _registered_method=True)


class PolymarketServiceServicer(object):
    """=============================================================================
    PolymarketService - Polymarket CLOB API proxy
    =============================================================================

    """

    def GetMarket(self, request, context):
        """Market data endpoints
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMarkets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSimplifiedMarkets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderBook(self, request, context):
        """Order book and pricing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMidpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSpread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTickSize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAndPostOrder(self, request, context):
        """Order management (requires credentials - handled by gateway)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAndPostMarketOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPositions(self, request, context):
        """Position and trade queries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOpenOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTradesHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPriceHistory(self, request, context):
        """Historical data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTradeTape(self, request, context):
        """``GetTradeTape`` (NOT ``GetTrades``) intentionally avoids colliding with
        the existing ``GetTradesHistory`` RPC above. The two have different
        semantics: ``GetTradesHistory`` is the gateway-managed wallet's own fills
        (authenticated /trades), while ``GetTradeTape`` is the public market-wide
        trade tape (authenticated /data/trades, optional token filter).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalanceAllowance(self, request, context):
        """Balance queries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolymarketServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMarket': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMarket,
                    request_deserializer=polymarket__pb2.PolymarketGetMarketRequest.FromString,
                    response_serializer=polymarket__pb2.PolymarketMarketResponse.SerializeToString,
            ),
            'GetMarkets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMarkets,
                    request_deserializer=polymarket__pb2.PolymarketGetMarketsRequest.FromString,
                    response_serializer=polymarket__pb2.PolymarketMarketsResponse.SerializeToString,
            ),
            'GetSimplifiedMarkets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSimplifiedMarkets,
                    request_deserializer=polymarket__pb2.PolymarketGetSimplifiedMarketsRequest.FromString,
                    response_serializer=polymarket__pb2.PolymarketSimplifiedMarketsResponse.SerializeToString,
            ),
            'GetOrderBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderBook,
                    request_deserializer=polymarket__pb2.PolymarketOrderBookRequest.FromString,
                    response_serializer=polymarket__pb2.PolymarketOrderBookResponse.SerializeToString,
            ),
            'GetMidpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMidpoint,
                    request_deserializer=polymarket__pb2.PolymarketMidpointRequest.FromString,
                    response_serializer=polymarket__pb2.PolymarketMidpointResponse.SerializeToString,
            ),
            'GetPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrice,
                    request_deserializer=polymarket__pb2.PolymarketPriceRequest.FromString,
                    response_serializer=polymarket__pb2.PolymarketPriceResponse.SerializeToString,
            ),
            'GetSpread': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSpread,
                    request_deserializer=polymarket__pb2.PolymarketSpreadRequest.FromString,
                    response_serializer=polymarket__pb2.PolymarketSpreadResponse.SerializeToString,
            ),
            'GetTickSize': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTickSize,
                    request_deserializer=polymarket__pb2.PolymarketTickSizeRequest.FromString,
                    response_serializer=polymarket__pb2.PolymarketTickSizeResponse.SerializeToString,
            ),
            'CreateAndPostOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAndPostOrder,
                    request_deserializer=polymarket__pb2.PolymarketCreateOrderRequest.FromString,
                    response_serializer=polymarket__pb2.PolymarketOrderResponse.SerializeToString,
            ),
            'CreateAndPostMarketOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAndPostMarketOrder,
                    request_deserializer=polymarket__pb2.PolymarketMarketOrderRequest.FromString,
                    response_serializer=polymarket__pb2.PolymarketOrderResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=polymarket__pb2.PolymarketCancelOrderRequest.FromString,
                    response_serializer=polymarket__pb2.PolymarketCancelResponse.SerializeToString,
            ),
            'CancelOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrders,
                    request_deserializer=polymarket__pb2.PolymarketCancelOrdersRequest.FromString,
                    response_serializer=polymarket__pb2.PolymarketCancelResponse.SerializeToString,
            ),
            'CancelAll': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelAll,
                    request_deserializer=polymarket__pb2.PolymarketCancelAllRequest.FromString,
                    response_serializer=polymarket__pb2.PolymarketCancelResponse.SerializeToString,
            ),
            'GetPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositions,
                    request_deserializer=polymarket__pb2.PolymarketGetPositionsRequest.FromString,
                    response_serializer=polymarket__pb2.PolymarketPositionsResponse.SerializeToString,
            ),
            'GetOpenOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOpenOrders,
                    request_deserializer=polymarket__pb2.PolymarketGetOpenOrdersRequest.FromString,
                    response_serializer=polymarket__pb2.PolymarketOpenOrdersResponse.SerializeToString,
            ),
            'GetTradesHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTradesHistory,
                    request_deserializer=polymarket__pb2.PolymarketGetTradesRequest.FromString,
                    response_serializer=polymarket__pb2.PolymarketTradesResponse.SerializeToString,
            ),
            'GetOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrder,
                    request_deserializer=polymarket__pb2.PolymarketGetOrderRequest.FromString,
                    response_serializer=polymarket__pb2.PolymarketOrderInfoResponse.SerializeToString,
            ),
            'GetPriceHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPriceHistory,
                    request_deserializer=polymarket__pb2.PolymarketGetPriceHistoryRequest.FromString,
                    response_serializer=polymarket__pb2.PolymarketPriceHistoryResponse.SerializeToString,
            ),
            'GetTradeTape': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTradeTape,
                    request_deserializer=polymarket__pb2.PolymarketGetTradeTapeRequest.FromString,
                    response_serializer=polymarket__pb2.PolymarketTradeTapeResponse.SerializeToString,
            ),
            'GetBalanceAllowance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalanceAllowance,
                    request_deserializer=polymarket__pb2.PolymarketBalanceAllowanceRequest.FromString,
                    response_serializer=polymarket__pb2.PolymarketBalanceAllowanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'almanak.gateway.proto.PolymarketService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('almanak.gateway.proto.PolymarketService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PolymarketService(object):
    """=============================================================================
    PolymarketService - Polymarket CLOB API proxy
    =============================================================================

    """

    @staticmethod
    def GetMarket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.PolymarketService/GetMarket',
            polymarket__pb2.PolymarketGetMarketRequest.SerializeToString,
            polymarket__pb2.PolymarketMarketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMarkets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.PolymarketService/GetMarkets',
            polymarket__pb2.PolymarketGetMarketsRequest.SerializeToString,
            polymarket__pb2.PolymarketMarketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSimplifiedMarkets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.PolymarketService/GetSimplifiedMarkets',
            polymarket__pb2.PolymarketGetSimplifiedMarketsRequest.SerializeToString,
            polymarket__pb2.PolymarketSimplifiedMarketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.PolymarketService/GetOrderBook',
            polymarket__pb2.PolymarketOrderBookRequest.SerializeToString,
            polymarket__pb2.PolymarketOrderBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMidpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.PolymarketService/GetMidpoint',
            polymarket__pb2.PolymarketMidpointRequest.SerializeToString,
            polymarket__pb2.PolymarketMidpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.PolymarketService/GetPrice',
            polymarket__pb2.PolymarketPriceRequest.SerializeToString,
            polymarket__pb2.PolymarketPriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSpread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.PolymarketService/GetSpread',
            polymarket__pb2.PolymarketSpreadRequest.SerializeToString,
            polymarket__pb2.PolymarketSpreadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTickSize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.PolymarketService/GetTickSize',
            polymarket__pb2.PolymarketTickSizeRequest.SerializeToString,
            polymarket__pb2.PolymarketTickSizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAndPostOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.PolymarketService/CreateAndPostOrder',
            polymarket__pb2.PolymarketCreateOrderRequest.SerializeToString,
            polymarket__pb2.PolymarketOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAndPostMarketOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.PolymarketService/CreateAndPostMarketOrder',
            polymarket__pb2.PolymarketMarketOrderRequest.SerializeToString,
            polymarket__pb2.PolymarketOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.PolymarketService/CancelOrder',
            polymarket__pb2.PolymarketCancelOrderRequest.SerializeToString,
            polymarket__pb2.PolymarketCancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.PolymarketService/CancelOrders',
            polymarket__pb2.PolymarketCancelOrdersRequest.SerializeToString,
            polymarket__pb2.PolymarketCancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.PolymarketService/CancelAll',
            polymarket__pb2.PolymarketCancelAllRequest.SerializeToString,
            polymarket__pb2.PolymarketCancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.PolymarketService/GetPositions',
            polymarket__pb2.PolymarketGetPositionsRequest.SerializeToString,
            polymarket__pb2.PolymarketPositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOpenOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.PolymarketService/GetOpenOrders',
            polymarket__pb2.PolymarketGetOpenOrdersRequest.SerializeToString,
            polymarket__pb2.PolymarketOpenOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTradesHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.PolymarketService/GetTradesHistory',
            polymarket__pb2.PolymarketGetTradesRequest.SerializeToString,
            polymarket__pb2.PolymarketTradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.PolymarketService/GetOrder',
            polymarket__pb2.PolymarketGetOrderRequest.SerializeToString,
            polymarket__pb2.PolymarketOrderInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPriceHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.PolymarketService/GetPriceHistory',
            polymarket__pb2.PolymarketGetPriceHistoryRequest.SerializeToString,
            polymarket__pb2.PolymarketPriceHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTradeTape(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.PolymarketService/GetTradeTape',
            polymarket__pb2.PolymarketGetTradeTapeRequest.SerializeToString,
            polymarket__pb2.PolymarketTradeTapeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalanceAllowance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/almanak.gateway.proto.PolymarketService/GetBalanceAllowance',
            polymarket__pb2.PolymarketBalanceAllowanceRequest.SerializeToString,
            polymarket__pb2.PolymarketBalanceAllowanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
