"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
VIB-4813 (Phase 5 of VIB-4808): Polymarket-specific RPCs relocated
from ``almanak/gateway/proto/gateway.proto`` so the gateway proto
layer no longer names individual connectors. The wire-level service
name is unchanged — ``package`` is intentionally still
``almanak.gateway.proto`` so that the fully-qualified gRPC method
paths (``/almanak.gateway.proto.PolymarketService/...``) remain
byte-identical to the pre-move version. Only the source-of-truth
proto file and the generated Python module location moved.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class PolymarketGetMarketRequest(_message.Message):
    """=============================================================================
    Polymarket Market Data Messages
    =============================================================================
    """

    DESCRIPTOR: _descriptor.Descriptor

    CONDITION_ID_FIELD_NUMBER: _builtins.int
    SLUG_FIELD_NUMBER: _builtins.int
    condition_id: _builtins.str
    """Backward-compatible alias for market ID"""
    slug: _builtins.str
    """Optional market slug"""
    def __init__(
        self,
        *,
        condition_id: _builtins.str = ...,
        slug: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["condition_id", b"condition_id", "slug", b"slug"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketGetMarketRequest: _TypeAlias = PolymarketGetMarketRequest  # noqa: Y015

@_typing.final
class PolymarketMarketResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONDITION_ID_FIELD_NUMBER: _builtins.int
    QUESTION_ID_FIELD_NUMBER: _builtins.int
    TOKENS_FIELD_NUMBER: _builtins.int
    REWARDS_DAILY_RATE_FIELD_NUMBER: _builtins.int
    REWARDS_MIN_SIZE_FIELD_NUMBER: _builtins.int
    REWARDS_MAX_SPREAD_FIELD_NUMBER: _builtins.int
    ACTIVE_FIELD_NUMBER: _builtins.int
    CLOSED_FIELD_NUMBER: _builtins.int
    ACCEPTING_ORDERS_FIELD_NUMBER: _builtins.int
    ACCEPTING_ORDER_TIMESTAMP_FIELD_NUMBER: _builtins.int
    MINIMUM_ORDER_SIZE_FIELD_NUMBER: _builtins.int
    MINIMUM_TICK_SIZE_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    MARKET_ID_FIELD_NUMBER: _builtins.int
    QUESTION_FIELD_NUMBER: _builtins.int
    SLUG_FIELD_NUMBER: _builtins.int
    OUTCOMES_FIELD_NUMBER: _builtins.int
    OUTCOME_PRICES_FIELD_NUMBER: _builtins.int
    CLOB_TOKEN_IDS_FIELD_NUMBER: _builtins.int
    VOLUME_FIELD_NUMBER: _builtins.int
    VOLUME_24HR_FIELD_NUMBER: _builtins.int
    LIQUIDITY_FIELD_NUMBER: _builtins.int
    END_DATE_FIELD_NUMBER: _builtins.int
    ENABLE_ORDER_BOOK_FIELD_NUMBER: _builtins.int
    MAKER_BASE_FEE_BPS_FIELD_NUMBER: _builtins.int
    TAKER_BASE_FEE_BPS_FIELD_NUMBER: _builtins.int
    BEST_BID_FIELD_NUMBER: _builtins.int
    BEST_ASK_FIELD_NUMBER: _builtins.int
    LAST_TRADE_PRICE_FIELD_NUMBER: _builtins.int
    EVENT_ID_FIELD_NUMBER: _builtins.int
    EVENT_SLUG_FIELD_NUMBER: _builtins.int
    GROUP_SLUG_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    RAW_JSON_FIELD_NUMBER: _builtins.int
    condition_id: _builtins.str
    question_id: _builtins.str
    rewards_daily_rate: _builtins.str
    rewards_min_size: _builtins.str
    rewards_max_spread: _builtins.str
    active: _builtins.bool
    closed: _builtins.bool
    accepting_orders: _builtins.bool
    accepting_order_timestamp: _builtins.str
    minimum_order_size: _builtins.str
    minimum_tick_size: _builtins.str
    success: _builtins.bool
    error: _builtins.str
    market_id: _builtins.str
    question: _builtins.str
    slug: _builtins.str
    volume: _builtins.str
    volume_24hr: _builtins.str
    liquidity: _builtins.str
    end_date: _builtins.str
    enable_order_book: _builtins.bool
    maker_base_fee_bps: _builtins.str
    taker_base_fee_bps: _builtins.str
    best_bid: _builtins.str
    best_ask: _builtins.str
    last_trade_price: _builtins.str
    event_id: _builtins.str
    event_slug: _builtins.str
    group_slug: _builtins.str
    raw_json: _builtins.str
    """Full Gamma market payload"""
    @_builtins.property
    def tokens(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Token IDs for outcomes"""

    @_builtins.property
    def outcomes(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def outcome_prices(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def clob_token_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def tags(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        condition_id: _builtins.str = ...,
        question_id: _builtins.str = ...,
        tokens: _abc.Iterable[_builtins.str] | None = ...,
        rewards_daily_rate: _builtins.str = ...,
        rewards_min_size: _builtins.str = ...,
        rewards_max_spread: _builtins.str = ...,
        active: _builtins.bool = ...,
        closed: _builtins.bool = ...,
        accepting_orders: _builtins.bool = ...,
        accepting_order_timestamp: _builtins.str = ...,
        minimum_order_size: _builtins.str = ...,
        minimum_tick_size: _builtins.str = ...,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
        market_id: _builtins.str = ...,
        question: _builtins.str = ...,
        slug: _builtins.str = ...,
        outcomes: _abc.Iterable[_builtins.str] | None = ...,
        outcome_prices: _abc.Iterable[_builtins.str] | None = ...,
        clob_token_ids: _abc.Iterable[_builtins.str] | None = ...,
        volume: _builtins.str = ...,
        volume_24hr: _builtins.str = ...,
        liquidity: _builtins.str = ...,
        end_date: _builtins.str = ...,
        enable_order_book: _builtins.bool = ...,
        maker_base_fee_bps: _builtins.str = ...,
        taker_base_fee_bps: _builtins.str = ...,
        best_bid: _builtins.str = ...,
        best_ask: _builtins.str = ...,
        last_trade_price: _builtins.str = ...,
        event_id: _builtins.str = ...,
        event_slug: _builtins.str = ...,
        group_slug: _builtins.str = ...,
        tags: _abc.Iterable[_builtins.str] | None = ...,
        raw_json: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accepting_order_timestamp", b"accepting_order_timestamp", "accepting_orders", b"accepting_orders", "active", b"active", "best_ask", b"best_ask", "best_bid", b"best_bid", "clob_token_ids", b"clob_token_ids", "closed", b"closed", "condition_id", b"condition_id", "enable_order_book", b"enable_order_book", "end_date", b"end_date", "error", b"error", "event_id", b"event_id", "event_slug", b"event_slug", "group_slug", b"group_slug", "last_trade_price", b"last_trade_price", "liquidity", b"liquidity", "maker_base_fee_bps", b"maker_base_fee_bps", "market_id", b"market_id", "minimum_order_size", b"minimum_order_size", "minimum_tick_size", b"minimum_tick_size", "outcome_prices", b"outcome_prices", "outcomes", b"outcomes", "question", b"question", "question_id", b"question_id", "raw_json", b"raw_json", "rewards_daily_rate", b"rewards_daily_rate", "rewards_max_spread", b"rewards_max_spread", "rewards_min_size", b"rewards_min_size", "slug", b"slug", "success", b"success", "tags", b"tags", "taker_base_fee_bps", b"taker_base_fee_bps", "tokens", b"tokens", "volume", b"volume", "volume_24hr", b"volume_24hr"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketMarketResponse: _TypeAlias = PolymarketMarketResponse  # noqa: Y015

@_typing.final
class PolymarketGetMarketsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NEXT_CURSOR_FIELD_NUMBER: _builtins.int
    FILTERS_JSON_FIELD_NUMBER: _builtins.int
    next_cursor: _builtins.str
    """Pagination cursor (optional)"""
    filters_json: _builtins.str
    """JSON-encoded MarketFilters payload"""
    def __init__(
        self,
        *,
        next_cursor: _builtins.str = ...,
        filters_json: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["filters_json", b"filters_json", "next_cursor", b"next_cursor"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketGetMarketsRequest: _TypeAlias = PolymarketGetMarketsRequest  # noqa: Y015

@_typing.final
class PolymarketMarketsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MARKETS_FIELD_NUMBER: _builtins.int
    NEXT_CURSOR_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    next_cursor: _builtins.str
    success: _builtins.bool
    error: _builtins.str
    @_builtins.property
    def markets(self) -> _containers.RepeatedCompositeFieldContainer[Global___PolymarketMarketResponse]: ...
    def __init__(
        self,
        *,
        markets: _abc.Iterable[Global___PolymarketMarketResponse] | None = ...,
        next_cursor: _builtins.str = ...,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "markets", b"markets", "next_cursor", b"next_cursor", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketMarketsResponse: _TypeAlias = PolymarketMarketsResponse  # noqa: Y015

@_typing.final
class PolymarketGetSimplifiedMarketsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NEXT_CURSOR_FIELD_NUMBER: _builtins.int
    next_cursor: _builtins.str
    """Pagination cursor (optional)"""
    def __init__(
        self,
        *,
        next_cursor: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["next_cursor", b"next_cursor"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketGetSimplifiedMarketsRequest: _TypeAlias = PolymarketGetSimplifiedMarketsRequest  # noqa: Y015

@_typing.final
class PolymarketSimplifiedMarket(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONDITION_ID_FIELD_NUMBER: _builtins.int
    TOKENS_FIELD_NUMBER: _builtins.int
    MIN_INCENTIVE_SIZE_FIELD_NUMBER: _builtins.int
    MAX_INCENTIVE_SPREAD_FIELD_NUMBER: _builtins.int
    ACTIVE_FIELD_NUMBER: _builtins.int
    CLOSED_FIELD_NUMBER: _builtins.int
    condition_id: _builtins.str
    min_incentive_size: _builtins.str
    max_incentive_spread: _builtins.str
    active: _builtins.bool
    closed: _builtins.bool
    @_builtins.property
    def tokens(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        condition_id: _builtins.str = ...,
        tokens: _abc.Iterable[_builtins.str] | None = ...,
        min_incentive_size: _builtins.str = ...,
        max_incentive_spread: _builtins.str = ...,
        active: _builtins.bool = ...,
        closed: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active", b"active", "closed", b"closed", "condition_id", b"condition_id", "max_incentive_spread", b"max_incentive_spread", "min_incentive_size", b"min_incentive_size", "tokens", b"tokens"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketSimplifiedMarket: _TypeAlias = PolymarketSimplifiedMarket  # noqa: Y015

@_typing.final
class PolymarketSimplifiedMarketsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MARKETS_FIELD_NUMBER: _builtins.int
    NEXT_CURSOR_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    next_cursor: _builtins.str
    success: _builtins.bool
    error: _builtins.str
    @_builtins.property
    def markets(self) -> _containers.RepeatedCompositeFieldContainer[Global___PolymarketSimplifiedMarket]: ...
    def __init__(
        self,
        *,
        markets: _abc.Iterable[Global___PolymarketSimplifiedMarket] | None = ...,
        next_cursor: _builtins.str = ...,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "markets", b"markets", "next_cursor", b"next_cursor", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketSimplifiedMarketsResponse: _TypeAlias = PolymarketSimplifiedMarketsResponse  # noqa: Y015

@_typing.final
class PolymarketOrderBookRequest(_message.Message):
    """=============================================================================
    Polymarket Order Book Messages
    =============================================================================
    """

    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_ID_FIELD_NUMBER: _builtins.int
    token_id: _builtins.str
    """Token ID for the outcome"""
    def __init__(
        self,
        *,
        token_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["token_id", b"token_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketOrderBookRequest: _TypeAlias = PolymarketOrderBookRequest  # noqa: Y015

@_typing.final
class PolymarketOrderBookLevel(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PRICE_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    price: _builtins.str
    """Price level"""
    size: _builtins.str
    """Size at this level"""
    def __init__(
        self,
        *,
        price: _builtins.str = ...,
        size: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["price", b"price", "size", b"size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketOrderBookLevel: _TypeAlias = PolymarketOrderBookLevel  # noqa: Y015

@_typing.final
class PolymarketOrderBookResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MARKET_FIELD_NUMBER: _builtins.int
    ASSET_ID_FIELD_NUMBER: _builtins.int
    HASH_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    BIDS_FIELD_NUMBER: _builtins.int
    ASKS_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    market: _builtins.str
    """Token ID"""
    asset_id: _builtins.str
    hash: _builtins.str
    timestamp: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    @_builtins.property
    def bids(self) -> _containers.RepeatedCompositeFieldContainer[Global___PolymarketOrderBookLevel]: ...
    @_builtins.property
    def asks(self) -> _containers.RepeatedCompositeFieldContainer[Global___PolymarketOrderBookLevel]: ...
    def __init__(
        self,
        *,
        market: _builtins.str = ...,
        asset_id: _builtins.str = ...,
        hash: _builtins.str = ...,
        timestamp: _builtins.int = ...,
        bids: _abc.Iterable[Global___PolymarketOrderBookLevel] | None = ...,
        asks: _abc.Iterable[Global___PolymarketOrderBookLevel] | None = ...,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["asks", b"asks", "asset_id", b"asset_id", "bids", b"bids", "error", b"error", "hash", b"hash", "market", b"market", "success", b"success", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketOrderBookResponse: _TypeAlias = PolymarketOrderBookResponse  # noqa: Y015

@_typing.final
class PolymarketMidpointRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_ID_FIELD_NUMBER: _builtins.int
    token_id: _builtins.str
    def __init__(
        self,
        *,
        token_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["token_id", b"token_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketMidpointRequest: _TypeAlias = PolymarketMidpointRequest  # noqa: Y015

@_typing.final
class PolymarketMidpointResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MIDPOINT_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    midpoint: _builtins.str
    """Midpoint price as decimal string"""
    success: _builtins.bool
    error: _builtins.str
    def __init__(
        self,
        *,
        midpoint: _builtins.str = ...,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "midpoint", b"midpoint", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketMidpointResponse: _TypeAlias = PolymarketMidpointResponse  # noqa: Y015

@_typing.final
class PolymarketPriceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_ID_FIELD_NUMBER: _builtins.int
    SIDE_FIELD_NUMBER: _builtins.int
    token_id: _builtins.str
    side: _builtins.str
    """"BUY" or "SELL" """
    def __init__(
        self,
        *,
        token_id: _builtins.str = ...,
        side: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["side", b"side", "token_id", b"token_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketPriceRequest: _TypeAlias = PolymarketPriceRequest  # noqa: Y015

@_typing.final
class PolymarketPriceResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PRICE_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    price: _builtins.str
    """Best price as decimal string"""
    success: _builtins.bool
    error: _builtins.str
    def __init__(
        self,
        *,
        price: _builtins.str = ...,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "price", b"price", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketPriceResponse: _TypeAlias = PolymarketPriceResponse  # noqa: Y015

@_typing.final
class PolymarketSpreadRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_ID_FIELD_NUMBER: _builtins.int
    token_id: _builtins.str
    def __init__(
        self,
        *,
        token_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["token_id", b"token_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketSpreadRequest: _TypeAlias = PolymarketSpreadRequest  # noqa: Y015

@_typing.final
class PolymarketSpreadResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SPREAD_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    spread: _builtins.str
    """Spread as decimal string"""
    success: _builtins.bool
    error: _builtins.str
    def __init__(
        self,
        *,
        spread: _builtins.str = ...,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "spread", b"spread", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketSpreadResponse: _TypeAlias = PolymarketSpreadResponse  # noqa: Y015

@_typing.final
class PolymarketTickSizeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_ID_FIELD_NUMBER: _builtins.int
    token_id: _builtins.str
    def __init__(
        self,
        *,
        token_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["token_id", b"token_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketTickSizeRequest: _TypeAlias = PolymarketTickSizeRequest  # noqa: Y015

@_typing.final
class PolymarketTickSizeResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TICK_SIZE_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    tick_size: _builtins.str
    """Minimum tick size"""
    success: _builtins.bool
    error: _builtins.str
    def __init__(
        self,
        *,
        tick_size: _builtins.str = ...,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "success", b"success", "tick_size", b"tick_size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketTickSizeResponse: _TypeAlias = PolymarketTickSizeResponse  # noqa: Y015

@_typing.final
class PolymarketCreateOrderRequest(_message.Message):
    """=============================================================================
    Polymarket Order Messages
    =============================================================================
    """

    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_ID_FIELD_NUMBER: _builtins.int
    PRICE_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    SIDE_FIELD_NUMBER: _builtins.int
    FEE_RATE_BPS_FIELD_NUMBER: _builtins.int
    EXPIRATION_FIELD_NUMBER: _builtins.int
    NONCE_FIELD_NUMBER: _builtins.int
    TIME_IN_FORCE_FIELD_NUMBER: _builtins.int
    token_id: _builtins.str
    """Token ID for the outcome"""
    price: _builtins.str
    """Limit price as decimal string"""
    size: _builtins.str
    """Order size as decimal string"""
    side: _builtins.str
    """"BUY" or "SELL" """
    fee_rate_bps: _builtins.str
    """Fee rate in basis points (optional, default "0")"""
    expiration: _builtins.int
    """Order expiration timestamp (optional, 0 for no expiration)"""
    nonce: _builtins.str
    """Optional nonce (auto-generated if empty)"""
    time_in_force: _builtins.str
    """"GTC", "FOK", "GTD" (optional, default "GTC")"""
    def __init__(
        self,
        *,
        token_id: _builtins.str = ...,
        price: _builtins.str = ...,
        size: _builtins.str = ...,
        side: _builtins.str = ...,
        fee_rate_bps: _builtins.str = ...,
        expiration: _builtins.int = ...,
        nonce: _builtins.str = ...,
        time_in_force: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["expiration", b"expiration", "fee_rate_bps", b"fee_rate_bps", "nonce", b"nonce", "price", b"price", "side", b"side", "size", b"size", "time_in_force", b"time_in_force", "token_id", b"token_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketCreateOrderRequest: _TypeAlias = PolymarketCreateOrderRequest  # noqa: Y015

@_typing.final
class PolymarketMarketOrderRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_ID_FIELD_NUMBER: _builtins.int
    AMOUNT_FIELD_NUMBER: _builtins.int
    SIDE_FIELD_NUMBER: _builtins.int
    FEE_RATE_BPS_FIELD_NUMBER: _builtins.int
    EXPIRATION_FIELD_NUMBER: _builtins.int
    NONCE_FIELD_NUMBER: _builtins.int
    WORST_PRICE_FIELD_NUMBER: _builtins.int
    token_id: _builtins.str
    amount: _builtins.str
    """USDC amount for buy, token amount for sell"""
    side: _builtins.str
    """"BUY" or "SELL" """
    fee_rate_bps: _builtins.str
    """Fee rate in basis points (optional)"""
    expiration: _builtins.int
    """Order expiration timestamp (optional)"""
    nonce: _builtins.str
    """Optional nonce"""
    worst_price: _builtins.str
    """Optional worst acceptable price"""
    def __init__(
        self,
        *,
        token_id: _builtins.str = ...,
        amount: _builtins.str = ...,
        side: _builtins.str = ...,
        fee_rate_bps: _builtins.str = ...,
        expiration: _builtins.int = ...,
        nonce: _builtins.str = ...,
        worst_price: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount", "expiration", b"expiration", "fee_rate_bps", b"fee_rate_bps", "nonce", b"nonce", "side", b"side", "token_id", b"token_id", "worst_price", b"worst_price"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketMarketOrderRequest: _TypeAlias = PolymarketMarketOrderRequest  # noqa: Y015

@_typing.final
class PolymarketOrderResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ORDER_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    SIZE_MATCHED_FIELD_NUMBER: _builtins.int
    TRANSACT_TIME_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    ERROR_CODE_FIELD_NUMBER: _builtins.int
    PRICE_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    AVG_FILL_PRICE_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    SETUP_TXS_FIELD_NUMBER: _builtins.int
    FEE_PUSD_FIELD_NUMBER: _builtins.int
    order_id: _builtins.str
    status: _builtins.str
    """"LIVE", "MATCHED", "CANCELLED", etc."""
    size_matched: _builtins.str
    transact_time: _builtins.str
    success: _builtins.bool
    error: _builtins.str
    error_code: _builtins.str
    price: _builtins.str
    size: _builtins.str
    avg_fill_price: _builtins.str
    created_at: _builtins.str
    fee_pusd: _builtins.str
    """VIB-3710: pUSD fee charged by the Polymarket operator at match time.
    Decimal string in pUSD (6-decimal) human units, e.g. "0.012345". Empty
    string when the order did not match (no fee yet) or when the response
    body did not carry an explicit fee field. Distinct from any signed-order
    fee — V2 fees are operator-set at match time and are NOT part of the
    EIP-712 payload.
    """
    @_builtins.property
    def setup_txs(self) -> _containers.RepeatedCompositeFieldContainer[Global___PolymarketSetupTx]:
        """VIB-3710: on-chain setup transactions submitted by _ensure_wallet_ready
        (token approvals + source-asset wrap to pUSD) before this order. Empty
        when allowances were already in place AND no wrap was needed. Populated
        exactly once per order — drained server-side after each response is built
        so the next order does not double-count the same gas spend.
        """

    def __init__(
        self,
        *,
        order_id: _builtins.str = ...,
        status: _builtins.str = ...,
        size_matched: _builtins.str = ...,
        transact_time: _builtins.str = ...,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
        error_code: _builtins.str = ...,
        price: _builtins.str = ...,
        size: _builtins.str = ...,
        avg_fill_price: _builtins.str = ...,
        created_at: _builtins.str = ...,
        setup_txs: _abc.Iterable[Global___PolymarketSetupTx] | None = ...,
        fee_pusd: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["avg_fill_price", b"avg_fill_price", "created_at", b"created_at", "error", b"error", "error_code", b"error_code", "fee_pusd", b"fee_pusd", "order_id", b"order_id", "price", b"price", "setup_txs", b"setup_txs", "size", b"size", "size_matched", b"size_matched", "status", b"status", "success", b"success", "transact_time", b"transact_time"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketOrderResponse: _TypeAlias = PolymarketOrderResponse  # noqa: Y015

@_typing.final
class PolymarketSetupTx(_message.Message):
    """VIB-3710: per-tx record of a Polymarket V2 setup transaction (token
    approval or pUSD wrap) submitted by the gateway before an order. The
    strategy container uses these to attribute MATIC gas spend to the
    position whose first BUY triggered the setup.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TX_HASH_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    GAS_USED_FIELD_NUMBER: _builtins.int
    GAS_PRICE_WEI_FIELD_NUMBER: _builtins.int
    TOTAL_COST_WEI_FIELD_NUMBER: _builtins.int
    tx_hash: _builtins.str
    description: _builtins.str
    """e.g. "Approve pUSD → CTF V2 exchange" """
    gas_used: _builtins.int
    gas_price_wei: _builtins.str
    """Decimal string for precision"""
    total_cost_wei: _builtins.str
    """gas_used * gas_price (Decimal string)"""
    def __init__(
        self,
        *,
        tx_hash: _builtins.str = ...,
        description: _builtins.str = ...,
        gas_used: _builtins.int = ...,
        gas_price_wei: _builtins.str = ...,
        total_cost_wei: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "gas_price_wei", b"gas_price_wei", "gas_used", b"gas_used", "total_cost_wei", b"total_cost_wei", "tx_hash", b"tx_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketSetupTx: _TypeAlias = PolymarketSetupTx  # noqa: Y015

@_typing.final
class PolymarketCancelOrderRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ORDER_ID_FIELD_NUMBER: _builtins.int
    order_id: _builtins.str
    def __init__(
        self,
        *,
        order_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["order_id", b"order_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketCancelOrderRequest: _TypeAlias = PolymarketCancelOrderRequest  # noqa: Y015

@_typing.final
class PolymarketCancelOrdersRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ORDER_IDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def order_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        order_ids: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["order_ids", b"order_ids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketCancelOrdersRequest: _TypeAlias = PolymarketCancelOrdersRequest  # noqa: Y015

@_typing.final
class PolymarketCancelAllRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MARKET_ID_FIELD_NUMBER: _builtins.int
    ASSET_ID_FIELD_NUMBER: _builtins.int
    market_id: _builtins.str
    """Optional: cancel only for specific market"""
    asset_id: _builtins.str
    """Optional: cancel only for specific asset"""
    def __init__(
        self,
        *,
        market_id: _builtins.str = ...,
        asset_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["asset_id", b"asset_id", "market_id", b"market_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketCancelAllRequest: _TypeAlias = PolymarketCancelAllRequest  # noqa: Y015

@_typing.final
class PolymarketCancelResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CANCELED_FIELD_NUMBER: _builtins.int
    NOT_CANCELED_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    @_builtins.property
    def canceled(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def not_canceled(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        canceled: _abc.Iterable[_builtins.str] | None = ...,
        not_canceled: _abc.Iterable[_builtins.str] | None = ...,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["canceled", b"canceled", "error", b"error", "not_canceled", b"not_canceled", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketCancelResponse: _TypeAlias = PolymarketCancelResponse  # noqa: Y015

@_typing.final
class PolymarketGetPositionsRequest(_message.Message):
    """=============================================================================
    Polymarket Position and Trade Messages
    =============================================================================

    Uses wallet address from gateway credentials
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___PolymarketGetPositionsRequest: _TypeAlias = PolymarketGetPositionsRequest  # noqa: Y015

@_typing.final
class PolymarketPosition(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ASSET_FIELD_NUMBER: _builtins.int
    CONDITION_ID_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    AVG_PRICE_FIELD_NUMBER: _builtins.int
    REALIZED_PNL_FIELD_NUMBER: _builtins.int
    CUR_PRICE_FIELD_NUMBER: _builtins.int
    MARKET_ID_FIELD_NUMBER: _builtins.int
    TOKEN_ID_FIELD_NUMBER: _builtins.int
    OUTCOME_FIELD_NUMBER: _builtins.int
    MARKET_QUESTION_FIELD_NUMBER: _builtins.int
    asset: _builtins.str
    """Token ID"""
    condition_id: _builtins.str
    size: _builtins.str
    avg_price: _builtins.str
    realized_pnl: _builtins.str
    cur_price: _builtins.str
    market_id: _builtins.str
    token_id: _builtins.str
    outcome: _builtins.str
    market_question: _builtins.str
    def __init__(
        self,
        *,
        asset: _builtins.str = ...,
        condition_id: _builtins.str = ...,
        size: _builtins.str = ...,
        avg_price: _builtins.str = ...,
        realized_pnl: _builtins.str = ...,
        cur_price: _builtins.str = ...,
        market_id: _builtins.str = ...,
        token_id: _builtins.str = ...,
        outcome: _builtins.str = ...,
        market_question: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["asset", b"asset", "avg_price", b"avg_price", "condition_id", b"condition_id", "cur_price", b"cur_price", "market_id", b"market_id", "market_question", b"market_question", "outcome", b"outcome", "realized_pnl", b"realized_pnl", "size", b"size", "token_id", b"token_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketPosition: _TypeAlias = PolymarketPosition  # noqa: Y015

@_typing.final
class PolymarketPositionsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    POSITIONS_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    @_builtins.property
    def positions(self) -> _containers.RepeatedCompositeFieldContainer[Global___PolymarketPosition]: ...
    def __init__(
        self,
        *,
        positions: _abc.Iterable[Global___PolymarketPosition] | None = ...,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "positions", b"positions", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketPositionsResponse: _TypeAlias = PolymarketPositionsResponse  # noqa: Y015

@_typing.final
class PolymarketGetOpenOrdersRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MARKET_ID_FIELD_NUMBER: _builtins.int
    ASSET_ID_FIELD_NUMBER: _builtins.int
    market_id: _builtins.str
    """Optional: filter by market"""
    asset_id: _builtins.str
    """Optional: filter by asset"""
    def __init__(
        self,
        *,
        market_id: _builtins.str = ...,
        asset_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["asset_id", b"asset_id", "market_id", b"market_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketGetOpenOrdersRequest: _TypeAlias = PolymarketGetOpenOrdersRequest  # noqa: Y015

@_typing.final
class PolymarketOpenOrder(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ORDER_ID_FIELD_NUMBER: _builtins.int
    MARKET_FIELD_NUMBER: _builtins.int
    ASSET_ID_FIELD_NUMBER: _builtins.int
    SIDE_FIELD_NUMBER: _builtins.int
    PRICE_FIELD_NUMBER: _builtins.int
    ORIGINAL_SIZE_FIELD_NUMBER: _builtins.int
    SIZE_MATCHED_FIELD_NUMBER: _builtins.int
    OUTCOME_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    EXPIRATION_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    order_id: _builtins.str
    market: _builtins.str
    asset_id: _builtins.str
    side: _builtins.str
    price: _builtins.str
    original_size: _builtins.str
    size_matched: _builtins.str
    outcome: _builtins.str
    status: _builtins.str
    expiration: _builtins.str
    created_at: _builtins.str
    def __init__(
        self,
        *,
        order_id: _builtins.str = ...,
        market: _builtins.str = ...,
        asset_id: _builtins.str = ...,
        side: _builtins.str = ...,
        price: _builtins.str = ...,
        original_size: _builtins.str = ...,
        size_matched: _builtins.str = ...,
        outcome: _builtins.str = ...,
        status: _builtins.str = ...,
        expiration: _builtins.str = ...,
        created_at: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["asset_id", b"asset_id", "created_at", b"created_at", "expiration", b"expiration", "market", b"market", "order_id", b"order_id", "original_size", b"original_size", "outcome", b"outcome", "price", b"price", "side", b"side", "size_matched", b"size_matched", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketOpenOrder: _TypeAlias = PolymarketOpenOrder  # noqa: Y015

@_typing.final
class PolymarketOpenOrdersResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ORDERS_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    @_builtins.property
    def orders(self) -> _containers.RepeatedCompositeFieldContainer[Global___PolymarketOpenOrder]: ...
    def __init__(
        self,
        *,
        orders: _abc.Iterable[Global___PolymarketOpenOrder] | None = ...,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "orders", b"orders", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketOpenOrdersResponse: _TypeAlias = PolymarketOpenOrdersResponse  # noqa: Y015

@_typing.final
class PolymarketGetTradesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MARKET_ID_FIELD_NUMBER: _builtins.int
    ASSET_ID_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    BEFORE_FIELD_NUMBER: _builtins.int
    AFTER_FIELD_NUMBER: _builtins.int
    market_id: _builtins.str
    """Optional: filter by market"""
    asset_id: _builtins.str
    """Optional: filter by asset"""
    limit: _builtins.int
    """Optional: limit results"""
    before: _builtins.str
    """Optional: pagination cursor"""
    after: _builtins.str
    """Optional: pagination cursor"""
    def __init__(
        self,
        *,
        market_id: _builtins.str = ...,
        asset_id: _builtins.str = ...,
        limit: _builtins.int = ...,
        before: _builtins.str = ...,
        after: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["after", b"after", "asset_id", b"asset_id", "before", b"before", "limit", b"limit", "market_id", b"market_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketGetTradesRequest: _TypeAlias = PolymarketGetTradesRequest  # noqa: Y015

@_typing.final
class PolymarketTrade(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRADE_ID_FIELD_NUMBER: _builtins.int
    MARKET_FIELD_NUMBER: _builtins.int
    ASSET_ID_FIELD_NUMBER: _builtins.int
    SIDE_FIELD_NUMBER: _builtins.int
    PRICE_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    FEE_RATE_BPS_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    MATCH_TIME_FIELD_NUMBER: _builtins.int
    TRANSACTION_HASH_FIELD_NUMBER: _builtins.int
    BUCKET_INDEX_FIELD_NUMBER: _builtins.int
    trade_id: _builtins.str
    market: _builtins.str
    asset_id: _builtins.str
    side: _builtins.str
    price: _builtins.str
    size: _builtins.str
    fee_rate_bps: _builtins.str
    status: _builtins.str
    match_time: _builtins.str
    transaction_hash: _builtins.str
    bucket_index: _builtins.str
    def __init__(
        self,
        *,
        trade_id: _builtins.str = ...,
        market: _builtins.str = ...,
        asset_id: _builtins.str = ...,
        side: _builtins.str = ...,
        price: _builtins.str = ...,
        size: _builtins.str = ...,
        fee_rate_bps: _builtins.str = ...,
        status: _builtins.str = ...,
        match_time: _builtins.str = ...,
        transaction_hash: _builtins.str = ...,
        bucket_index: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["asset_id", b"asset_id", "bucket_index", b"bucket_index", "fee_rate_bps", b"fee_rate_bps", "market", b"market", "match_time", b"match_time", "price", b"price", "side", b"side", "size", b"size", "status", b"status", "trade_id", b"trade_id", "transaction_hash", b"transaction_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketTrade: _TypeAlias = PolymarketTrade  # noqa: Y015

@_typing.final
class PolymarketTradesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRADES_FIELD_NUMBER: _builtins.int
    NEXT_CURSOR_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    next_cursor: _builtins.str
    success: _builtins.bool
    error: _builtins.str
    @_builtins.property
    def trades(self) -> _containers.RepeatedCompositeFieldContainer[Global___PolymarketTrade]: ...
    def __init__(
        self,
        *,
        trades: _abc.Iterable[Global___PolymarketTrade] | None = ...,
        next_cursor: _builtins.str = ...,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "next_cursor", b"next_cursor", "success", b"success", "trades", b"trades"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketTradesResponse: _TypeAlias = PolymarketTradesResponse  # noqa: Y015

@_typing.final
class PolymarketGetOrderRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ORDER_ID_FIELD_NUMBER: _builtins.int
    order_id: _builtins.str
    def __init__(
        self,
        *,
        order_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["order_id", b"order_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketGetOrderRequest: _TypeAlias = PolymarketGetOrderRequest  # noqa: Y015

@_typing.final
class PolymarketOrderInfoResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ORDER_ID_FIELD_NUMBER: _builtins.int
    MARKET_FIELD_NUMBER: _builtins.int
    ASSET_ID_FIELD_NUMBER: _builtins.int
    SIDE_FIELD_NUMBER: _builtins.int
    PRICE_FIELD_NUMBER: _builtins.int
    ORIGINAL_SIZE_FIELD_NUMBER: _builtins.int
    SIZE_MATCHED_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    OUTCOME_FIELD_NUMBER: _builtins.int
    OWNER_FIELD_NUMBER: _builtins.int
    EXPIRATION_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    ASSOCIATE_TRADES_JSON_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    order_id: _builtins.str
    market: _builtins.str
    asset_id: _builtins.str
    side: _builtins.str
    price: _builtins.str
    original_size: _builtins.str
    size_matched: _builtins.str
    status: _builtins.str
    outcome: _builtins.str
    owner: _builtins.str
    expiration: _builtins.str
    created_at: _builtins.str
    associate_trades_json: _builtins.str
    """JSON array of associated trades"""
    success: _builtins.bool
    error: _builtins.str
    def __init__(
        self,
        *,
        order_id: _builtins.str = ...,
        market: _builtins.str = ...,
        asset_id: _builtins.str = ...,
        side: _builtins.str = ...,
        price: _builtins.str = ...,
        original_size: _builtins.str = ...,
        size_matched: _builtins.str = ...,
        status: _builtins.str = ...,
        outcome: _builtins.str = ...,
        owner: _builtins.str = ...,
        expiration: _builtins.str = ...,
        created_at: _builtins.str = ...,
        associate_trades_json: _builtins.str = ...,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["asset_id", b"asset_id", "associate_trades_json", b"associate_trades_json", "created_at", b"created_at", "error", b"error", "expiration", b"expiration", "market", b"market", "order_id", b"order_id", "original_size", b"original_size", "outcome", b"outcome", "owner", b"owner", "price", b"price", "side", b"side", "size_matched", b"size_matched", "status", b"status", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketOrderInfoResponse: _TypeAlias = PolymarketOrderInfoResponse  # noqa: Y015

@_typing.final
class PolymarketBalanceAllowanceRequest(_message.Message):
    """=============================================================================
    Polymarket Balance Messages
    =============================================================================
    """

    DESCRIPTOR: _descriptor.Descriptor

    ASSET_TYPE_FIELD_NUMBER: _builtins.int
    TOKEN_ID_FIELD_NUMBER: _builtins.int
    asset_type: _builtins.str
    """"COLLATERAL" or "CONDITIONAL" """
    token_id: _builtins.str
    """Required for CONDITIONAL type"""
    def __init__(
        self,
        *,
        asset_type: _builtins.str = ...,
        token_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["asset_type", b"asset_type", "token_id", b"token_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketBalanceAllowanceRequest: _TypeAlias = PolymarketBalanceAllowanceRequest  # noqa: Y015

@_typing.final
class PolymarketBalanceAllowanceResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BALANCE_FIELD_NUMBER: _builtins.int
    ALLOWANCE_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    balance: _builtins.str
    allowance: _builtins.str
    success: _builtins.bool
    error: _builtins.str
    def __init__(
        self,
        *,
        balance: _builtins.str = ...,
        allowance: _builtins.str = ...,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allowance", b"allowance", "balance", b"balance", "error", b"error", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketBalanceAllowanceResponse: _TypeAlias = PolymarketBalanceAllowanceResponse  # noqa: Y015

@_typing.final
class PolymarketGetPriceHistoryRequest(_message.Message):
    """=============================================================================
    Polymarket Historical Data Messages
    =============================================================================

    ``GetPriceHistory`` proxies the public CLOB ``/prices-history`` endpoint.
    Either ``interval`` (predefined: 1m/1h/6h/1d/1w/max) or
    ``start_ts``+``end_ts`` (custom Unix-second range) may be provided — they
    are mutually exclusive at the source endpoint, validated server-side.
    ``fidelity`` (resolution in minutes) is optional in either mode.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_ID_FIELD_NUMBER: _builtins.int
    INTERVAL_FIELD_NUMBER: _builtins.int
    START_TS_FIELD_NUMBER: _builtins.int
    END_TS_FIELD_NUMBER: _builtins.int
    FIDELITY_FIELD_NUMBER: _builtins.int
    token_id: _builtins.str
    """CLOB token id (YES or NO outcome)"""
    interval: _builtins.str
    """Optional: 1m / 1h / 6h / 1d / 1w / max"""
    start_ts: _builtins.int
    """Optional: Unix seconds, requires end_ts"""
    end_ts: _builtins.int
    """Optional: Unix seconds, requires start_ts"""
    fidelity: _builtins.int
    """Optional: minute-resolution buckets"""
    def __init__(
        self,
        *,
        token_id: _builtins.str = ...,
        interval: _builtins.str = ...,
        start_ts: _builtins.int = ...,
        end_ts: _builtins.int = ...,
        fidelity: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["end_ts", b"end_ts", "fidelity", b"fidelity", "interval", b"interval", "start_ts", b"start_ts", "token_id", b"token_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketGetPriceHistoryRequest: _TypeAlias = PolymarketGetPriceHistoryRequest  # noqa: Y015

@_typing.final
class PolymarketHistoricalPrice(_message.Message):
    """One CLOB ``/prices-history`` point. Polymarket returns ``t`` (Unix seconds)
    and ``p`` (probability 0.0-1.0); we mirror them as int64 + string-decimal.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: _builtins.int
    PRICE_FIELD_NUMBER: _builtins.int
    timestamp: _builtins.int
    """Unix seconds (UTC)"""
    price: _builtins.str
    """Decimal string (probability 0.0-1.0)"""
    def __init__(
        self,
        *,
        timestamp: _builtins.int = ...,
        price: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["price", b"price", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketHistoricalPrice: _TypeAlias = PolymarketHistoricalPrice  # noqa: Y015

@_typing.final
class PolymarketPriceHistoryResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_ID_FIELD_NUMBER: _builtins.int
    INTERVAL_FIELD_NUMBER: _builtins.int
    PRICES_FIELD_NUMBER: _builtins.int
    START_TIME_FIELD_NUMBER: _builtins.int
    END_TIME_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    token_id: _builtins.str
    interval: _builtins.str
    """Echo of the resolved interval ("custom" if range)"""
    start_time: _builtins.int
    """Unix seconds of first price (0 if empty)"""
    end_time: _builtins.int
    """Unix seconds of last price (0 if empty)"""
    success: _builtins.bool
    error: _builtins.str
    @_builtins.property
    def prices(self) -> _containers.RepeatedCompositeFieldContainer[Global___PolymarketHistoricalPrice]: ...
    def __init__(
        self,
        *,
        token_id: _builtins.str = ...,
        interval: _builtins.str = ...,
        prices: _abc.Iterable[Global___PolymarketHistoricalPrice] | None = ...,
        start_time: _builtins.int = ...,
        end_time: _builtins.int = ...,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["end_time", b"end_time", "error", b"error", "interval", b"interval", "prices", b"prices", "start_time", b"start_time", "success", b"success", "token_id", b"token_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketPriceHistoryResponse: _TypeAlias = PolymarketPriceHistoryResponse  # noqa: Y015

@_typing.final
class PolymarketGetTradeTapeRequest(_message.Message):
    """``GetTradeTape`` proxies the authenticated CLOB ``/data/trades`` endpoint.
    ``token_id`` is optional (omit for market-wide tape). ``limit`` is capped
    at 500 by the upstream and defaults to 100 when zero.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_ID_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    token_id: _builtins.str
    """Optional: filter trades by CLOB token id"""
    limit: _builtins.int
    """Default 100, capped at 500 server-side"""
    def __init__(
        self,
        *,
        token_id: _builtins.str = ...,
        limit: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["limit", b"limit", "token_id", b"token_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketGetTradeTapeRequest: _TypeAlias = PolymarketGetTradeTapeRequest  # noqa: Y015

@_typing.final
class PolymarketHistoricalTrade(_message.Message):
    """One trade from the tape. Mirrors ``HistoricalTrade`` model fields plus
    any market/asset metadata the upstream returns (kept for compatibility
    with future provider-side enrichment).
    """

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    TOKEN_ID_FIELD_NUMBER: _builtins.int
    SIDE_FIELD_NUMBER: _builtins.int
    PRICE_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    MAKER_FIELD_NUMBER: _builtins.int
    TAKER_FIELD_NUMBER: _builtins.int
    MARKET_ID_FIELD_NUMBER: _builtins.int
    ASSET_ID_FIELD_NUMBER: _builtins.int
    OUTCOME_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """Trade id (sometimes ``tradeId`` upstream)"""
    token_id: _builtins.str
    """CLOB token id"""
    side: _builtins.str
    """"BUY" or "SELL" """
    price: _builtins.str
    """Decimal string"""
    size: _builtins.str
    """Decimal string"""
    timestamp: _builtins.int
    """Unix seconds (UTC)"""
    maker: _builtins.str
    """Optional maker address"""
    taker: _builtins.str
    """Optional taker address"""
    market_id: _builtins.str
    """Optional condition / market id when present"""
    asset_id: _builtins.str
    """Optional asset id (alias for token_id upstream)"""
    outcome: _builtins.str
    """Optional "YES"/"NO" if upstream tags it"""
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        token_id: _builtins.str = ...,
        side: _builtins.str = ...,
        price: _builtins.str = ...,
        size: _builtins.str = ...,
        timestamp: _builtins.int = ...,
        maker: _builtins.str = ...,
        taker: _builtins.str = ...,
        market_id: _builtins.str = ...,
        asset_id: _builtins.str = ...,
        outcome: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["asset_id", b"asset_id", "id", b"id", "maker", b"maker", "market_id", b"market_id", "outcome", b"outcome", "price", b"price", "side", b"side", "size", b"size", "taker", b"taker", "timestamp", b"timestamp", "token_id", b"token_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketHistoricalTrade: _TypeAlias = PolymarketHistoricalTrade  # noqa: Y015

@_typing.final
class PolymarketTradeTapeResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRADES_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    @_builtins.property
    def trades(self) -> _containers.RepeatedCompositeFieldContainer[Global___PolymarketHistoricalTrade]: ...
    def __init__(
        self,
        *,
        trades: _abc.Iterable[Global___PolymarketHistoricalTrade] | None = ...,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "success", b"success", "trades", b"trades"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolymarketTradeTapeResponse: _TypeAlias = PolymarketTradeTapeResponse  # noqa: Y015
