from almanak.integrations._base import ImportRef, Integration

# Retired or renamed Binance markets that must not be treated as tradeable
# execution-grade proxies by either price or OHLCV surfaces.
BINANCE_UNSAFE_MARKET_BASES = frozenset({"FTM", "RNDR"})

INTEGRATION = Integration(
    name="binance",
    market_symbols={
        ("ETH", "USDT"): "ETHUSDT",
        ("WETH", "USDT"): "ETHUSDT",
        ("WETH", "USDC"): "ETHUSDC",
        ("BTC", "USDT"): "BTCUSDT",
        ("WBTC", "USDT"): "BTCUSDT",
        ("WBTC", "USDC"): "BTCUSDC",
        ("BTCB", "USDT"): "BTCUSDT",
        ("BTCB", "USDC"): "BTCUSDC",
        ("CBBTC", "USDT"): "BTCUSDT",
        ("CBBTC", "USDC"): "BTCUSDC",
        ("SOL", "USDT"): "SOLUSDT",
        ("ARB", "USDT"): "ARBUSDT",
        ("OP", "USDT"): "OPUSDT",
        ("AVAX", "USDT"): "AVAXUSDT",
        ("WAVAX", "USDT"): "AVAXUSDT",
        ("MATIC", "USDT"): "POLUSDT",
        ("WMATIC", "USDT"): "POLUSDT",
        ("POL", "USDT"): "POLUSDT",
        ("WPOL", "USDT"): "POLUSDT",
        ("BNB", "USDT"): "BNBUSDT",
        ("WBNB", "USDT"): "BNBUSDT",
        ("LINK", "USDT"): "LINKUSDT",
        ("UNI", "USDT"): "UNIUSDT",
        ("AAVE", "USDT"): "AAVEUSDT",
        ("GMX", "USDT"): "GMXUSDT",
        ("CRV", "USDT"): "CRVUSDT",
        ("PENDLE", "USDT"): "PENDLEUSDT",
        ("DAI", "USDT"): "DAIUSDT",
        ("LDO", "USDT"): "LDOUSDT",
        ("MKR", "USDT"): "MKRUSDT",
        ("SNX", "USDT"): "SNXUSDT",
        ("COMP", "USDT"): "COMPUSDT",
        ("SUSHI", "USDT"): "SUSHIUSDT",
        ("YFI", "USDT"): "YFIUSDT",
        ("BAL", "USDT"): "BALUSDT",
        ("1INCH", "USDT"): "1INCHUSDT",
        ("CAKE", "USDT"): "CAKEUSDT",
        ("JOE", "USDT"): "JOEUSDT",
        ("OKB", "USDT"): "OKBUSDT",
        ("WOKB", "USDT"): "OKBUSDT",
        ("S", "USDT"): "SUSDT",
        ("DOGE", "USDT"): "DOGEUSDT",
        ("XETH", "USDT"): "ETHUSDT",
        ("XBTC", "USDT"): "BTCUSDT",
        ("WS", "USDT"): "SUSDT",
        ("USDC", "USDT"): "USDCUSDT",
        ("SHIB", "USDT"): "SHIBUSDT",
        ("APE", "USDT"): "APEUSDT",
        ("PEPE", "USDT"): "PEPEUSDT",
        ("WLD", "USDT"): "WLDUSDT",
        ("STX", "USDT"): "STXUSDT",
        ("INJ", "USDT"): "INJUSDT",
        ("TIA", "USDT"): "TIAUSDT",
        ("SEI", "USDT"): "SEIUSDT",
        ("SUI", "USDT"): "SUIUSDT",
        ("APT", "USDT"): "APTUSDT",
        ("FET", "USDT"): "FETUSDT",
        ("RNDR", "USDT"): "RNDRUSDT",
        ("GRT", "USDT"): "GRTUSDT",
        ("FIL", "USDT"): "FILUSDT",
    },
    gateway_price_source=ImportRef(
        module="almanak.integrations.binance.gateway.factory",
        attribute="BinancePriceSourceFactory",
        order=20,
    ),
    price_source_blocked_by_groups=frozenset({"venue_oracle"}),
    gateway_api_client=ImportRef(
        module="almanak.integrations.binance.gateway.factory",
        attribute="BinanceClientFactory",
    ),
)
