"""Canonical connector self-registration interface."""

from __future__ import annotations

from almanak.connectors._connector_descriptor import (
    CONNECTOR_DESCRIPTOR_REGISTRY,
    CONNECTOR_REGISTRY,
    KNOWN_PROTOCOL_VENDORS,
    MATRIX_CHAIN_DISPLAY_ORDER,
    BacktestRiskDecl,
    BacktestStrategyTypeDecl,
    CapabilitiesSpec,
    Connector,
    ConnectorDescriptor,
    ConnectorDescriptorRegistry,
    ConnectorDiscoveryError,
    ConnectorRegistry,
    DexVolumeDecl,
    FeeModelDecl,
    FundingHistoryDecl,
    FungibleLpCloseDecl,
    ImportRef,
    LendingReadDecl,
    LiquidationDefault,
    MetadataAmountEncoding,
    PerpsReadDecl,
    PositionReadDecl,
    StrategyMatrixEntry,
    SupportedChainsSpec,
    VaultRepresentativeSpec,
    YieldPokeDecl,
    vendor_protocol_map,
)

__all__ = [
    "CONNECTOR_DESCRIPTOR_REGISTRY",
    "CONNECTOR_REGISTRY",
    "BacktestRiskDecl",
    "BacktestStrategyTypeDecl",
    "CapabilitiesSpec",
    "Connector",
    "ConnectorDescriptor",
    "ConnectorDescriptorRegistry",
    "ConnectorDiscoveryError",
    "ConnectorRegistry",
    "DexVolumeDecl",
    "FeeModelDecl",
    "FundingHistoryDecl",
    "ImportRef",
    "KNOWN_PROTOCOL_VENDORS",
    "LendingReadDecl",
    "LiquidationDefault",
    "MATRIX_CHAIN_DISPLAY_ORDER",
    "MetadataAmountEncoding",
    "PerpsReadDecl",
    "FungibleLpCloseDecl",
    "PositionReadDecl",
    "StrategyMatrixEntry",
    "SupportedChainsSpec",
    "VaultRepresentativeSpec",
    "vendor_protocol_map",
    "YieldPokeDecl",
]
