"""Gateway-only Binance price source.

Uses the Binance public ticker API (no API key required) to fetch token prices.
Very generous rate limits (1200 req/min) compared to CoinGecko free tier.

This is especially useful for chains without Chainlink feeds (e.g., Mantle)
where CoinGecko free tier rate-limits aggressively.
"""

import asyncio
import logging
import time
from datetime import UTC, datetime
from decimal import Decimal, InvalidOperation

import aiohttp

from almanak.framework.data.interfaces import (
    BasePriceSource,
    DataSourceUnavailable,
    PriceResult,
)
from almanak.framework.data.tokens import TokenRef, is_pegged
from almanak.framework.data.tokens.defaults import DEFAULT_TOKENS
from almanak.gateway.utils.ssl_context import build_ssl_context
from almanak.integrations.binance.integration import BINANCE_UNSAFE_MARKET_BASES

logger = logging.getLogger(__name__)

# The spot-price source intentionally owns a narrower, reviewed catalogue than
# the general Binance market-symbol manifest used by OHLCV/instrument surfaces.
# A manifest row does not automatically become an execution-grade price proxy.
_TOKEN_TO_BINANCE_SYMBOL: dict[str, str] = {
    "ETH": "ETHUSDT",
    "WETH": "ETHUSDT",
    "BTC": "BTCUSDT",
    "WBTC": "BTCUSDT",
    "BTCB": "BTCUSDT",
    "CBBTC": "BTCUSDT",
    "SOL": "SOLUSDT",
    "ARB": "ARBUSDT",
    "AVAX": "AVAXUSDT",
    "WAVAX": "AVAXUSDT",
    # MATICUSDT is a delisted ghost quote. Polygon aliases must use POLUSDT.
    "POL": "POLUSDT",
    "MATIC": "POLUSDT",
    "WMATIC": "POLUSDT",
    "WPOL": "POLUSDT",
    "BNB": "BNBUSDT",
    "WBNB": "BNBUSDT",
    "LINK": "LINKUSDT",
    "UNI": "UNIUSDT",
    "AAVE": "AAVEUSDT",
    "OP": "OPUSDT",
    "GMX": "GMXUSDT",
    "CRV": "CRVUSDT",
    "PENDLE": "PENDLEUSDT",
    "LDO": "LDOUSDT",
    "S": "SUSDT",
    "WS": "SUSDT",
    "DOGE": "DOGEUSDT",
    "CAKE": "CAKEUSDT",
    "JOE": "JOEUSDT",
    "OKB": "OKBUSDT",
    "WOKB": "OKBUSDT",
    "XETH": "ETHUSDT",
    "XBTC": "BTCUSDT",
}

# Known retired/renamed symbols must never fall through to dynamic ticker
# probing: Binance can retain ghost ticker rows after the tradeable market is
# gone, and those rows are not safe at execution-grade confidence.
_DYNAMIC_RESOLUTION_DENYLIST = BINANCE_UNSAFE_MARKET_BASES

# Quote currencies to try when dynamically resolving unknown tokens (VIB-645).
# Order matters: USDT is the most common, USDC and FDUSD are fallbacks.
_DYNAMIC_QUOTE_CANDIDATES = ("USDT", "USDC", "FDUSD")

# TTL for negative cache entries (tokens confirmed not on Binance).
_NEGATIVE_CACHE_TTL = 4 * 3600  # 4 hours

# Confidence assigned to a corroborated dynamic resolution. Below the curated
# table's 1.0 because the quote pair was discovered at runtime rather than
# reviewed, but the *identity* behind it is reviewed (see the gate below).
_DYNAMIC_CONFIDENCE = 0.9

# ALM-3185 — identity-keyed corroboration for dynamic ticker probing.
#
# Ticker symbols collide across projects: Velodrome's VELO on Optimism and Velo
# Labs' VELO on Binance are unrelated assets sharing three letters. A ticker
# probe (`{SYMBOL}USDT`) cannot tell them apart, so probing on the symbol alone
# invents a confidently wrong price. That price is not merely one vote in the
# aggregate: ``PriceAggregator`` has no confidence-based eligibility filter —
# a single surviving source is returned as-is and its confidence only *labels*
# the result — so when the address-based sources are rate-limited the probe
# result IS the price. Demotion therefore cannot contain this; the seam has to
# fail closed.
#
# The gate: dynamic probing runs only when the *identity* of the on-chain token
# — its CoinGecko asset id, carried on the ``ResolvedToken`` the caller resolved
# from the contract address — is explicitly linked to a Binance base ticker
# here. Keyed on identity, never on the symbol, so a same-ticker stranger can
# never satisfy a row curated for a different project.
#
# Adding a row is a reviewed action with exactly the weight of adding a
# ``_TOKEN_TO_BINANCE_SYMBOL`` row. A row asserts "the project CoinGecko calls
# <id> is the project Binance lists under base <BASE>", verified per row against
# both venues. It must NEVER be generated by joining two catalogues on a symbol
# string — that join is precisely the collision this gate exists to defeat.
#
# Empty by default. The token registry carries no venue link today
# (``tokens.json`` has ``coingecko_id`` but no Binance id), so the gate is
# closed and Binance abstains for uncurated tokens. Abstaining is the correct
# outcome: the address-based sources (DexScreener, CoinGecko-by-address,
# on-chain oracles) price long-tail tokens without the identity ambiguity, and
# a missing Binance vote costs far less than a confident wrong one.
_COINGECKO_ID_TO_BINANCE_BASE: dict[str, str] = {}


def _curated_binance_symbol(token_upper: str) -> str | None:
    """Return only a pair explicitly approved for the spot-price source."""
    return _TOKEN_TO_BINANCE_SYMBOL.get(token_upper)


def _corroborated_binance_base(resolved_token: object | None) -> str | None:
    """Return the reviewed Binance base ticker for a resolved token's identity.

    ALM-3185. Returns ``None`` — closing the gate — whenever the caller supplied
    no resolved token, the resolved token carries no CoinGecko id, or that id has
    no reviewed venue link. Duck-typed on purpose: the aggregator's
    ``resolved_token`` is typed ``object | None`` on this interface, and anything
    that is not a real identity (a dict, a bare symbol string, ``None``) must
    fail closed rather than raise.
    """
    coingecko_id = getattr(resolved_token, "coingecko_id", None)
    if not isinstance(coingecko_id, str):
        return None
    return _COINGECKO_ID_TO_BINANCE_BASE.get(coingecko_id.strip().lower())


def _registry_peg(resolved_token: object | None) -> Decimal | None:
    """Return a peg only for a strict registry-backed token identity."""
    token_ref = getattr(resolved_token, "token_ref", None)
    return is_pegged(token_ref) if isinstance(token_ref, TokenRef) else None


class BinancePriceSource(BasePriceSource):
    """Binance public API price source.

    Uses the /api/v3/ticker/price endpoint (no API key needed).
    Rate limit: 1200 req/min (very generous).

    For tokens not in the static symbol map, dynamic resolution probes
    {BASE}USDT, {BASE}USDC, {BASE}FDUSD against the API to discover which quote
    pair is live. Successful lookups are cached; failures are negative-cached
    for 4h.

    Dynamic resolution is **corroboration-gated** (ALM-3185): the base ticker
    comes from ``_COINGECKO_ID_TO_BINANCE_BASE`` keyed on the resolved token's
    identity, never from the requested symbol. A token with no reviewed venue
    link gets no price from this source at all — see the gate's rationale above.
    """

    _API_BASE = "https://api.binance.com"

    def __init__(self, cache_ttl: int = 30, request_timeout: float = 5.0) -> None:
        self._cache_ttl = cache_ttl
        self._request_timeout = request_timeout
        self._cache: dict[str, tuple[PriceResult, float]] = {}
        self._session: aiohttp.ClientSession | None = None
        self._session_loop: asyncio.AbstractEventLoop | None = None
        # Dynamic resolution caches (VIB-645). Keyed by the *corroborated Binance
        # base ticker*, not the requested token symbol (ALM-3185): a symbol-keyed
        # cache would let an uncorroborated caller read an entry established for a
        # different project that happens to share the ticker.
        self._dynamic_symbol_cache: dict[str, str] = {}  # BASE -> resolved Binance symbol
        self._negative_cache: dict[str, float] = {}  # BASE -> timestamp of failed lookup
        logger.info("Initialized BinancePriceSource (cache_ttl=%ds)", cache_ttl)

    async def _get_session(self) -> aiohttp.ClientSession:
        current_loop = asyncio.get_running_loop()
        if self._session is not None and not self._session.closed:
            if self._session_loop is not None and self._session_loop is not current_loop:
                try:
                    await self._session.close()
                except Exception:
                    pass
                self._session = None
                self._session_loop = None
        if self._session is None or self._session.closed:
            timeout = aiohttp.ClientTimeout(total=self._request_timeout)
            connector = aiohttp.TCPConnector(ssl=build_ssl_context())
            self._session = aiohttp.ClientSession(timeout=timeout, connector=connector)
            self._session_loop = current_loop
        return self._session

    async def close(self) -> None:
        if self._session and not self._session.closed:
            await self._session.close()
            self._session = None
            self._session_loop = None

    async def get_price(self, token: str, quote: str = "USD", *, resolved_token: object | None = None) -> PriceResult:
        quote_upper = quote.upper()

        # Binance pairs are quoted in USDT. Accept "USD" and "USDT" as equivalent;
        # reject any other quote currency to avoid mislabeled prices.
        if quote_upper not in ("USD", "USDT"):
            raise DataSourceUnavailable(
                source=self.source_name,
                reason=f"Binance only supports USD/USDT quotes, got '{quote}'",
            )

        token_upper = token.upper()

        # Synthetic stablecoin prices require exact chain+address identity.
        peg = _registry_peg(resolved_token)
        if peg is not None:
            token_ref = getattr(resolved_token, "token_ref", None)
            assert isinstance(token_ref, TokenRef)
            identity = token_ref.identity_key
            return PriceResult(
                price=peg,
                source=self.source_name,
                timestamp=datetime.now(UTC),
                confidence=1.0,
                peg_tokens=(f"{identity[0]}:{identity[1]}",),
            )

        # Look up Binance symbol: curated table -> corroborated dynamic resolution.
        binance_symbol = _curated_binance_symbol(token_upper)
        confidence = 1.0
        dynamic_base: str | None = None

        if not binance_symbol:
            dynamic_base = self._gate_dynamic_base(token_upper, resolved_token)
            binance_symbol = await self._resolve_dynamic_symbol(dynamic_base)
            confidence = _DYNAMIC_CONFIDENCE

        # ALM-3185: the price cache is keyed by the *resolved pair*, not by the
        # requested symbol, and is read only after the gate has run. A symbol-keyed
        # row read before the gate would hand an uncorroborated caller the price
        # another project's corroborated call had just cached under the same
        # ticker — the collision the gate exists to prevent, arriving via cache.
        cache_key = f"{binance_symbol}/{quote_upper}"
        if cache_key in self._cache:
            result, cached_at = self._cache[cache_key]
            if time.time() - cached_at < self._cache_ttl:
                return result

        try:
            result = await self._fetch_price(binance_symbol, cache_key, confidence)
            return result
        except DataSourceUnavailable:
            raise
        except (aiohttp.ClientError, TimeoutError, InvalidOperation, ValueError, TypeError, KeyError) as e:
            # Evict dynamic cache on API error (the pair may have been delisted)
            if dynamic_base is not None and dynamic_base in self._dynamic_symbol_cache:
                del self._dynamic_symbol_cache[dynamic_base]
                logger.warning("Evicted dynamic Binance mapping for %s after API error: %s", dynamic_base, e)
            # Check for stale cache
            if cache_key in self._cache:
                stale_result, _ = self._cache[cache_key]
                return PriceResult(
                    price=stale_result.price,
                    source=self.source_name,
                    timestamp=stale_result.timestamp,
                    confidence=0.7,
                    stale=True,
                    peg_tokens=stale_result.peg_tokens,
                )
            raise DataSourceUnavailable(
                source=self.source_name,
                reason=f"Binance request failed: {e}",
            ) from e

    def _gate_dynamic_base(self, token_upper: str, resolved_token: object | None) -> str:
        """Return the Binance base ticker dynamic probing is authorised to use.

        ALM-3185. This is the corroboration gate. It never derives a base from
        the requested symbol; the base comes from the reviewed identity link, so
        an unknown token whose ticker happens to collide with a listed Binance
        pair cannot reach the probe at all.

        Raises:
            DataSourceUnavailable: the token is denylisted, or its identity has
                no reviewed Binance link. Both are ordinary source abstentions —
                the aggregator records them as errors and prices the token from
                the remaining (address-based) sources.
        """
        if token_upper in _DYNAMIC_RESOLUTION_DENYLIST:
            raise DataSourceUnavailable(
                source=self.source_name,
                reason=f"Token '{token_upper}' is not approved for Binance dynamic price resolution",
            )

        base = _corroborated_binance_base(resolved_token)
        if base is None:
            raise DataSourceUnavailable(
                source=self.source_name,
                reason=(
                    f"Token '{token_upper}' has no corroborated Binance listing; dynamic ticker "
                    "probing is gated on a reviewed identity link (ALM-3185)"
                ),
            )

        # A retired base stays blocked however it was reached: a link pointing at
        # a ghost ticker is exactly as unsafe as a symbol that resolves to one.
        if base in _DYNAMIC_RESOLUTION_DENYLIST:
            raise DataSourceUnavailable(
                source=self.source_name,
                reason=f"Token '{base}' is not approved for Binance dynamic price resolution",
            )
        return base

    async def _resolve_dynamic_symbol(self, base: str) -> str:
        """Resolve a corroborated base ticker to a live Binance pair.

        Callers must have cleared :meth:`_gate_dynamic_base` first — ``base`` is a
        reviewed venue ticker, never a caller-supplied symbol.

        Raises:
            DataSourceUnavailable: no live pair for this base (negative-cached, or
                every quote candidate returned not-found).
        """
        cached = self._dynamic_symbol_cache.get(base)
        if cached:
            return cached

        neg_ts = self._negative_cache.get(base)
        if neg_ts and (time.time() - neg_ts) < _NEGATIVE_CACHE_TTL:
            raise DataSourceUnavailable(
                source=self.source_name,
                reason=f"Token '{base}' not available on Binance (negative-cached)",
            )

        # Dynamic resolution: probe candidate quote pairs (VIB-645)
        binance_symbol = await self._resolve_binance_symbol(base)
        if not binance_symbol:
            raise DataSourceUnavailable(
                source=self.source_name,
                reason=f"Token '{base}' not found on Binance (tried {', '.join(_DYNAMIC_QUOTE_CANDIDATES)})",
            )
        return binance_symbol

    async def _fetch_price(self, binance_symbol: str, cache_key: str, confidence: float) -> PriceResult:
        """Fetch a price from Binance for a given trading pair symbol."""
        session = await self._get_session()
        url = f"{self._API_BASE}/api/v3/ticker/price?symbol={binance_symbol}"
        async with session.get(url) as resp:
            if resp.status in (429, 418) or resp.status >= 500:
                text = await resp.text()
                raise DataSourceUnavailable(
                    source=self.source_name,
                    reason=f"Binance API transient error {resp.status}: {text}",
                )
            if resp.status != 200:
                text = await resp.text()
                raise ValueError(f"Binance API returned {resp.status}: {text}")
            data = await resp.json()
            price_str = data.get("price")
            if price_str is None:
                raise ValueError("Binance response missing 'price' field")
            price = Decimal(str(price_str))

            result = PriceResult(
                price=price,
                source=self.source_name,
                timestamp=datetime.now(UTC),
                confidence=confidence,
            )
            self._cache[cache_key] = (result, time.time())
            return result

    async def _resolve_binance_symbol(self, base: str) -> str | None:
        """Find the live Binance trading pair for a corroborated base ticker.

        Probes {BASE}USDT, {BASE}USDC, {BASE}FDUSD against the ticker API.
        Returns the first valid pair, or None if no pair exists.
        Successful lookups are cached in ``_dynamic_symbol_cache`` under ``base``.

        ``base`` is a reviewed venue ticker supplied by :meth:`_gate_dynamic_base`
        — never a caller-supplied token symbol (ALM-3185). This method performs
        quote discovery only; it does not decide *whether* probing is allowed.
        """
        # Guard against non-alphanumeric bases being injected into URLs
        if not base.isalnum():
            return None

        session = await self._get_session()
        saw_transient_error = False
        for quote in _DYNAMIC_QUOTE_CANDIDATES:
            candidate = f"{base}{quote}"
            url = f"{self._API_BASE}/api/v3/ticker/price?symbol={candidate}"
            try:
                async with session.get(url) as resp:
                    if resp.status == 200:
                        data = await resp.json()
                        if data.get("price"):
                            self._dynamic_symbol_cache[base] = candidate
                            logger.warning(
                                "Dynamically resolved Binance pair for %s -> %s (not in static map)",
                                base,
                                candidate,
                            )
                            return candidate
                    elif resp.status in (429, 418) or resp.status >= 500:
                        saw_transient_error = True
                        continue
            except (aiohttp.ClientError, TimeoutError):
                saw_transient_error = True
                continue
        # Only negative-cache if all probes got definitive 4xx (not-found) responses
        if not saw_transient_error:
            self._negative_cache[base] = time.time()
        else:
            logger.debug("Skipping negative cache for %s due to transient errors during probe", base)
        return None

    @property
    def source_name(self) -> str:
        return "binance"

    @property
    def supported_tokens(self) -> list[str]:
        pegged_symbols = {token.symbol for token in DEFAULT_TOKENS if token.peg_class is not None}
        return list(_TOKEN_TO_BINANCE_SYMBOL.keys()) + sorted(pegged_symbols)

    @property
    def cache_ttl_seconds(self) -> int:
        return self._cache_ttl
