"""Writer-safe exact-venue contracts."""

from .client import observe_exact_venue_data
from .consumer import ExactVenueDataConsumer, ExactVenueDataProvider, ExactVenueDataRegistryAdapter
from .data import (
    EXACT_VENUE_DATA_SCHEMA_VERSION,
    DepthParameters,
    ExactVenueDataResult,
    ExactVenueFeatureParameters,
    ExactVenueFeatureRequest,
    ExactVenueObservation,
    OhlcvParameters,
    QuoteParameters,
    ReferencePriceMethod,
    ReferencePriceParameters,
    TwapParameters,
    VenueDataAnchorKind,
    VenueDataFailure,
    VenueDataFailureReason,
    VenueDataFailureState,
    VenueDataProvenance,
    VenueObservationAnchor,
)
from .gateway import GatewayClientExactVenueDataGateway, GatewayClientVenueVerificationGateway
from .permissions import VenuePermissionEvidence, reconcile_venue_permissions
from .provider import BaseExactVenueDataProvider, ExactVenueDataGateway, GatewayBlockIdentity, GatewayExactOhlcvResponse
from .receipt import (
    VenueReceiptCorrelationError,
    VenueReceiptEvidence,
    correlate_verified_venue_receipts,
    reconcile_verified_venue_receipts,
)
from .types import (
    VENUE_BINDING_SCHEMA_VERSION,
    ExactVenueBinding,
    VenueBindingComponent,
    VenueBindingFailure,
    VenueBindingFailureReason,
    VenueBindingFailureState,
    VenueObservedFact,
    VenueReferenceNamespace,
    VenueTargetRef,
    VenueTargetRole,
    VenueVerificationEvidence,
    VenueVerificationResult,
    VerifiedVenueBinding,
    build_verified_venue_binding,
    canonical_venue_binding_preimage_bytes,
)
from .verifier import BaseVenueVerifier, VenueVerificationGateway, VenueVerificationRequest

__all__ = [
    "EXACT_VENUE_DATA_SCHEMA_VERSION",
    "VENUE_BINDING_SCHEMA_VERSION",
    "BaseVenueVerifier",
    "BaseExactVenueDataProvider",
    "DepthParameters",
    "ExactVenueBinding",
    "ExactVenueDataResult",
    "ExactVenueDataConsumer",
    "ExactVenueDataProvider",
    "ExactVenueFeatureParameters",
    "ExactVenueFeatureRequest",
    "ExactVenueObservation",
    "OhlcvParameters",
    "QuoteParameters",
    "ReferencePriceMethod",
    "ReferencePriceParameters",
    "TwapParameters",
    "VenueBindingComponent",
    "VenueBindingFailure",
    "VenueBindingFailureReason",
    "VenueBindingFailureState",
    "VenueDataFailure",
    "VenueDataAnchorKind",
    "VenueDataFailureReason",
    "VenueDataFailureState",
    "VenueDataProvenance",
    "VenueObservedFact",
    "VenueReferenceNamespace",
    "VenueReceiptCorrelationError",
    "VenueReceiptEvidence",
    "VenueTargetRef",
    "VenueTargetRole",
    "VenueVerificationEvidence",
    "VenueVerificationGateway",
    "GatewayClientVenueVerificationGateway",
    "GatewayClientExactVenueDataGateway",
    "ExactVenueDataGateway",
    "GatewayBlockIdentity",
    "GatewayExactOhlcvResponse",
    "VenueVerificationRequest",
    "VenueVerificationResult",
    "VerifiedVenueBinding",
    "VenueObservationAnchor",
    "VenuePermissionEvidence",
    "build_verified_venue_binding",
    "canonical_venue_binding_preimage_bytes",
    "correlate_verified_venue_receipts",
    "reconcile_verified_venue_receipts",
    "reconcile_venue_permissions",
    "observe_exact_venue_data",
]
