"""Fluid vault (NFT-CDP) connector manifest — ``fluid_vault``."""

from __future__ import annotations

from almanak.connectors._base.types import ProtocolKind
from almanak.connectors._connector import (
    Connector,
    ImportRef,
    LendingReadDecl,
    MetadataAmountEncoding,
    StrategyMatrixEntry,
)
from almanak.connectors._strategy_base.address_table import AddressTableSpec
from almanak.connectors._strategy_base.protocol_ownership import CapabilitiesSpec

CONNECTOR = Connector(
    # Vault NFT-CDP borrow surface (Phase 3, VIB-5031, ADR r2 Q0): a second
    # thin manifest over the fluid package. ``market_id`` (the vault address)
    # is REQUIRED here while the fluid/fToken key REJECTS it — the protocol
    # key is the Phase-2/Phase-3 disambiguator, decided at intent
    # construction, zero heuristics. All implementation modules live in
    # ``almanak.connectors.fluid`` (one codebase, two manifests).
    name="fluid_vault",
    kind=ProtocolKind.LENDING,
    # NOTHING aliases here: ``fluid_lending`` stays an alias of ``fluid``
    # (the fToken surface) — collapsing it onto the vault key would fork
    # position keys and accounting confidence (ADR r2 blocker 1).
    aliases=(),
    address_tables=(
        AddressTableSpec(
            protocol="fluid_vault",
            module="almanak.connectors._fluid_core.addresses",
            attribute="FLUID_VAULT",
        ),
    ),
    compiler=ImportRef(
        module="almanak.connectors._fluid_core.vault_compiler",
        attribute="FluidVaultCompiler",
    ),
    # Vault receipts (factory-gated nftId + signed LogOperate deltas) route
    # to their own parser — never the DEX/fToken parser.
    receipt_parser_connector=ImportRef(
        module="almanak.connectors.fluid_vault.receipt_parser_provider",
        attribute="FluidVaultReceiptParserConnector",
    ),
    # Pre-ledger result enrichment: stamps FluidVaultOperateData (the §6.3
    # nftId home) into transaction_ledger.extracted_data_json.
    runner_hook_connector=ImportRef(
        module="almanak.connectors._fluid_core.runner_hooks",
        attribute="FluidVaultRunnerHookConnector",
    ),
    # Zodiac role surface (ADR §7.1): operate() on each pinned vault
    # (+ send_value for native-collateral vaults) and the two scoped token
    # approvals — generated by the discovery vectors in
    # fluid/vault_permission_hints.py (re-exported by this package's
    # permission_hints module); NO ERC-721 surface. The ``fluid_vault``
    # ContractRoleSpec (empty role table — per-market operate targets are
    # not router/pool roles) is published from the FLUID manifest's
    # ``fluid/contract_roles.py`` tuple, the registry's one-module-per-file
    # discovery contract (aerodrome precedent).
    # ``requires_market_id=True`` — intent construction rejects fluid_vault
    # intents without the vault address (Morpho Blue isolated-market shape).
    capabilities=CapabilitiesSpec(
        keys=("fluid_vault",),
        module="almanak.connectors._fluid_core.capabilities",
    ),
    # Bespoke positionsByUser account-state read (ADR §3.2): vault-oracle
    # protocol-truth HF + injected-seam USD legs. The market table doubles as
    # the pinned type-1 vault universe the compiler enforces.
    lending_read=LendingReadDecl(
        account_state=ImportRef(
            module="almanak.connectors._fluid_core.vault_lending_read",
            attribute="ACCOUNT_STATE_READ_SPEC",
        ),
        market_table=ImportRef(
            module="almanak.connectors._fluid_core.addresses",
            attribute="FLUID_VAULT_MARKETS",
        ),
        aliases=(),
    ),
    # The vault compiler ships metadata amounts wei-encoded
    # (``supply_amount`` / ``borrow_amount`` / ... = token base units); the
    # orchestrator's pre-flight balance check and description formatter
    # derive the classification from this declaration (VIB-3747 / VIB-4851 C1).
    metadata_amount_encoding=MetadataAmountEncoding(lending="wei"),
    strategy_intents=("SUPPLY", "BORROW", "REPAY", "WITHDRAW"),
    # Checkpoint-1 scope — the exact lending universe, no cross-product
    # over-claim (compile-time chain guard retained as defense-in-depth).
    strategy_chains=("arbitrum", "base"),
    strategy_matrix_entries=(
        StrategyMatrixEntry(
            matrix_name="fluid_vault",
            category="lending",
            chains=frozenset(("arbitrum", "base")),
        ),
    ),
)

__all__ = ["CONNECTOR"]
